let favorites=JSON.parse(localStorage.getItem('br-fav')||'[]'),mode='all',favOnly=false,decisionMode='all';
const profile={regions:['Sicilia','Mezzogiorno','Italia','UE'],sectors:['Energia','Elettronica','Automazione','Industria 4.0','Digitalizzazione','Sostenibilità'],kw:['IoT','digital twin','automazione','energia','ricerca industriale','AI','efficienza energetica']};
function score(o){let n=20;n+=Math.min(30,o.sectors.filter(x=>profile.sectors.includes(x)).length*10);n+=Math.min(25,o.kw.filter(x=>profile.kw.some(k=>x.toLowerCase().includes(k.toLowerCase())||k.toLowerCase().includes(x.toLowerCase()))).length*5);n+=o.territory.some(t=>profile.regions.includes(t)||t==='Italia'||t==='UE')?15:-15;n+=(o.fit?.length||0)*2;return Math.max(0,Math.min(100,n))}
function classify(o){const s=score(o),b=(o.beneficiaries||'').toLowerCase(),r=(o.risks||[]).join(' ').toLowerCase();if(b.includes('mi non appare beneficiario')||b.includes('irccs')||r.includes('beneficiario o solo partner'))return {k:'PARTNER',c:'partner',why:'MI non è il beneficiario naturale; opportunità da presidiare come partner o fornitore tecnologico.'};if(o.type==='Investimenti'||o.type==='Formazione')return {k:'INVESTIMENTI',c:'invest',why:'Misura utile soprattutto per finanziare investimenti o competenze interne MI.'};if(s>=70&&o.territory.some(t=>['Sicilia','Mezzogiorno','Italia','UE'].includes(t)))return {k:'CANDIDARSI',c:'apply',why:'Compatibilità alta con profilo, territorio e competenze MI.'};if(s<55)return {k:'SCARTARE',c:'discard',why:'Compatibilità insufficiente rispetto al profilo MI o ai vincoli noti.'};return {k:'PARTNER',c:'partner',why:'Fit tecnico discreto ma conviene entrare tramite partenariato o ruolo specialistico.'}}
function days(o){if(!o.deadline)return 999;return Math.ceil((new Date(o.deadline+'T23:59:59')-new Date())/86400000)}
function urgency(o){let d=days(o);if(d<0)return 'Chiuso/da verificare';if(d<=15)return d+' gg · URGENTE';if(d<=45)return d+' gg';return o.date}
function setMode(m){mode=m;['allTab','rdTab','investTab','trainingTab'].forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById(m==='all'?'allTab':m==='R&S'?'rdTab':m==='Investimenti'?'investTab':'trainingTab').classList.add('active');render()}
function setDecision(m){decisionMode=m;document.querySelectorAll('[data-decision]').forEach(x=>x.classList.toggle('active',x.dataset.decision===m));render()}
function showOnlyFav(){favOnly=!favOnly;render()}
function render(){let q=document.getElementById('q').value.toLowerCase(),t=document.getElementById('territory').value,min=+document.getElementById('min').value,e=document.getElementById('expense').value;let all=grants.map(o=>({o,s:score(o),d:classify(o)}));let list=all.filter(x=>(mode==='all'||x.o.type===mode)&&(decisionMode==='all'||x.d.k===decisionMode)&&(!favOnly||favorites.includes(x.o.id))&&(t==='Tutti i territori'||x.o.territory.includes(t))&&x.s>=min&&(!e||x.o.expenses.includes(e))&&(x.o.title+' '+x.o.what+' '+x.o.kw.join(' ')+' '+x.o.expenses.join(' ')+' '+x.o.sectors.join(' ')).toLowerCase().includes(q)).sort((a,b)=>b.s-a.s);document.getElementById('grantGrid').innerHTML=list.length?list.map(x=>card(x.o,x.s,x.d)).join(''):'<div class="empty">Nessun bando con questi filtri.</div>';document.getElementById('best').textContent=all.filter(x=>x.s>=70).length;document.getElementById('total').textContent=grants.length;document.getElementById('scanned').textContent=sourceRegistry.filter(x=>x.status==='Scansionata').length+'/'+sourceRegistry.length;document.getElementById('newCount').textContent=grants.filter(x=>x.fresh).length;document.getElementById('urgent').textContent=grants.filter(x=>days(x)>=0&&days(x)<=45).length;document.getElementById('applyCount').textContent=all.filter(x=>x.d.k==='CANDIDARSI').length;document.getElementById('partnerCount').textContent=all.filter(x=>x.d.k==='PARTNER').length;document.getElementById('investCount').textContent=all.filter(x=>x.d.k==='INVESTIMENTI').length}
function card(o,s,d){return `<div class="grant" onclick="detail('${o.id}')"><div class="grant-head"><span class="score ${s>=80?'hi':s>=60?'mid':'low'}">${s}</span><div><div><span class="decision-badge ${d.c}">${d.k}</span> ${o.fresh?'<span class="badge fresh">NUOVO</span>':''} <span class="badge">${o.type}</span></div><h3>${o.title}</h3><div class="muted" style="font-size:12px">${o.source} · ${urgency(o)}</div></div><button class="star ${favorites.includes(o.id)?'on':''}" onclick="event.stopPropagation();fav('${o.id}')">★</button></div><div class="quick"><div class="qbox"><small>Cosa finanzia</small><b>${o.what}</b></div><div class="qbox"><small>Dimensione progetto</small><b>${o.budget}</b></div><div class="qbox"><small>Agevolazione</small><b>${o.grant}</b></div></div><div class="why"><b>Decisione:</b> ${d.why}</div></div>`}
function fav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('br-fav',JSON.stringify(favorites));render()}
function detail(id){let o=grants.find(x=>x.id===id),s=score(o),d=classify(o);document.getElementById('portal').innerHTML=`<div class="overlay" onclick="if(event.target===this)closeP()"><div class="modal"><button class="close" onclick="closeP()">×</button><div><span class="decision-badge ${d.c}">${d.k}</span> ${o.territory.map(z=>`<span class="badge">${z}</span>`).join('')}</div><h2>${o.title}</h2><div class="muted">${o.source} · ${urgency(o)}</div><div class="decision"><div class="qbox"><small>Fit MI</small><b>${s}/100</b></div><div class="qbox"><small>Decisione</small><b>${d.k}</b></div><div class="qbox"><small>Progetto</small><b>${o.budget}</b></div><div class="qbox"><small>Agevolazione</small><b>${o.grant}</b></div></div><div class="signal ${d.c==='discard'?'warn':'good'}"><b>${d.k}</b> — ${d.why}</div><div class="section"><h3>In una frase: di cosa si occupa</h3><p>${o.what}</p></div><div class="cols"><div><div class="section"><h3>Chi può partecipare</h3><p>${o.beneficiaries}</p></div><div class="section"><h3>Cosa finanzia / spese ammissibili</h3><div>${o.expenses.map(z=>`<span class="chip">${z}</span>`).join('')}</div></div></div><div><div class="section"><h3>Perché interessa a MI</h3>${o.fit.map(z=>`<div class="signal good">✓ ${z}</div>`).join('')}</div><div class="section"><h3>Attenzioni / vincoli</h3>${o.risks.map(z=>`<div class="signal warn">! ${z}</div>`).join('')}</div></div></div><div class="section"><h3>Azione consigliata</h3><p><b>${o.next}</b></p></div><div class="section"><h3>Link ufficiale del bando</h3><div class="official">${o.url}</div><p><a class="btn" target="_blank" rel="noopener" href="${o.url}">Apri bando ufficiale ↗</a></p></div></div></div>`}
function closeP(){document.getElementById('portal').innerHTML=''}
document.getElementById('sourcegrid').innerHTML=sourceRegistry.map(x=>`<div class="source"><div style="display:flex;justify-content:space-between;gap:8px"><b>${x.n}</b><span class="status ${x.status==='Scansionata'?'done':''}">${x.status}</span></div><div class="muted" style="font-size:12px;margin:4px 0">${x.s} · ultimo controllo ${x.last}</div><div style="font-size:13px;margin-bottom:6px">${x.d}</div><div style="font-size:12px;margin-bottom:6px">Rilevati: <b>${x.found}</b></div><a target="_blank" rel="noopener" href="${x.u}">Portale ufficiale ↗</a></div>`).join('');render();