import { useMemo, useState } from 'react'
import './App.css'

type Decision = 'CANDIDARSI' | 'PARTNER' | 'INVESTIMENTO' | 'SCARTARE'
type Priority = 'A' | 'B' | 'C'
type Grant = { id:string; title:string; decision:Decision; priority:Priority; source:string; territory:string[]; deadline:string; grant:string; budget:string; beneficiaries:string; what:string; expenses:string[]; partners:string; sectors:string[]; keywords:string[]; fit:string[]; risks:string[]; reason:string; next:string; url:string; fresh?:boolean }
type Source = { name:string; scope:string; status:'scanned'|'planned'; last:string; found:number; fresh:number; url:string }

const sources:Source[]=[
{name:'MIMIT - Incentivi',scope:'Italia',status:'scanned',last:'24/08/2026 17:31',found:4,fresh:1,url:'https://www.mimit.gov.it/it/incentivi'},
{name:'Invitalia - Incentivi e strumenti',scope:'Italia',status:'scanned',last:'24/08/2026 17:31',found:3,fresh:0,url:'https://www.invitalia.it/incentivi-e-strumenti'},
{name:'Regione Lombardia - Bandi e Servizi',scope:'Lombardia',status:'scanned',last:'24/08/2026 17:31',found:4,fresh:1,url:'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/ricerca-innovazione'},
{name:'Open Innovation Lombardia',scope:'Lombardia',status:'scanned',last:'24/08/2026 17:31',found:1,fresh:0,url:'https://www.openinnovation.regione.lombardia.it/it/bandi-e-sperimentazioni'},
{name:'EuroInfoSicilia / PR FESR Sicilia',scope:'Sicilia',status:'planned',last:'—',found:0,fresh:0,url:'https://www.euroinfosicilia.it/'},
{name:'EU Funding & Tenders Portal',scope:'UE',status:'planned',last:'—',found:0,fresh:0,url:'https://ec.europa.eu/info/funding-tenders/opportunities/portal/'},
{name:'CINEA - LIFE',scope:'UE',status:'planned',last:'—',found:0,fresh:0,url:'https://cinea.ec.europa.eu/life-calls-proposals-2026_en'},
{name:'European Innovation Council',scope:'UE',status:'planned',last:'—',found:0,fresh:0,url:'https://eic.ec.europa.eu/eic-funding-opportunities/eic-2026-work-programme_en'}]

const grants:Grant[]=[
{id:'scoperta',title:'Scoperta imprenditoriale II (2026)',decision:'CANDIDARSI',priority:'A',source:'MIMIT',territory:['Sicilia','Mezzogiorno'],deadline:'2026-11-26',grant:'40% finanziamento agevolato + 30–40% contributo',budget:'1–5 M€',beneficiaries:'Imprese con almeno 2 bilanci; PMI, grandi imprese e centri di ricerca secondo i requisiti',what:'R&S per nuovi o migliori prodotti, processi e servizi',expenses:['Personale R&S','Consulenza','Prototipi','Ricerca contrattuale'],partners:'Collaborazione obbligatoria o quota R&S esterna',sectors:['Industria 4.0','Elettronica','Energia'],keywords:['IoT','digital twin','automazione','ricerca industriale'],fit:['Sicilia eleggibile','Forte coerenza con IoT, digital twin, automazione ed energia','Dimensione adatta a progetto strutturato MI'],risks:['Budget minimo 1 M€','Collaborazione obbligatoria','Serve unità locale di progetto nel Mezzogiorno'],reason:'Opportunità diretta: MI può costruire una proposta R&S propria con partner tecnico/universitario.',next:'Definire una idea R&S prioritaria e costruire un partenariato con budget ≥1 M€.',url:'https://www.mimit.gov.it/it/incentivi/scoperta-imprenditoriale-2026'},
{id:'sostenibili',title:'Investimenti sostenibili 4.0 – Bando 2026',decision:'INVESTIMENTO',priority:'A',source:'MIMIT',territory:['Sicilia','Mezzogiorno'],deadline:'2026-12-31',grant:'Fino al 75%',budget:'750 k€–5 M€',beneficiaries:'PMI del Mezzogiorno secondo i requisiti del bando',what:'Macchinari, impianti, software e interventi 4.0/efficienza energetica',expenses:['Macchinari e impianti','Software e licenze','Consulenza','Efficienza energetica'],partners:'Nessun partenariato R&S richiesto',sectors:['Industria 4.0','Energia','Digitalizzazione','Sostenibilità'],keywords:['Transizione 4.0','automazione','efficienza energetica'],fit:['Sicilia eleggibile','Molto forte per digitalizzazione e impiantistica interna','Copertura finanziaria elevata'],risks:['Investimento minimo 750 k€','Serve programma cantierabile','Verificare requisiti PMI'],reason:'Da usare come incentivo per un piano di investimento interno MI, non come progetto R&S.',next:'Preparare lista investimenti, preventivi e risparmi energetici/digitali attesi.',url:'https://www.mimit.gov.it/it/normativa/decreti-direttoriali/decreto-direttoriale-5-agosto-2026-investimenti-sostenibili-4-0-bando-2026'},
{id:'voucher-cloud-cyber',title:'Voucher Cloud & Cybersecurity',decision:'INVESTIMENTO',priority:'A',fresh:true,source:'MIMIT',territory:['Sicilia','Mezzogiorno','Italia'],deadline:'2027-01-20',grant:'Voucher su servizi/prodotti ammessi',budget:'150 M€ dotazione',beneficiaries:'PMI e lavoratori autonomi secondo requisiti della misura',what:'Servizi e prodotti cloud e cybersecurity',expenses:['Software e licenze','Consulenza'],partners:'Nessun partenariato R&S',sectors:['Digitalizzazione','Elettronica'],keywords:['cloud','cybersecurity','sicurezza','backup'],fit:['Utile per sicurezza IT/OT, cloud e backup MI','Sicilia nella quota territoriale riservata','Iter più semplice di una R&S'],risks:['Verificare massimali','Fornitori abilitati','Non finanzia R&S proprietaria'],reason:'Incentivo diretto per rafforzare infrastruttura digitale e cybersecurity aziendale.',next:'Mappare spese cloud, backup, sicurezza OT/IT e fornitori abilitati.',url:'https://www.mimit.gov.it/it/incentivi/sostegno-alla-domanda-di-servizi-di-cloud-computing-e-cyber-security'},
{id:'competenze',title:'Sviluppo competenze specialistiche delle PMI',decision:'CANDIDARSI',priority:'B',source:'Invitalia',territory:['Sicilia','Mezzogiorno'],deadline:'2026-12-21',grant:'Contributo formazione',budget:'Programma formativo',beneficiaries:'PMI del Mezzogiorno secondo lo sportello',what:'Formazione su innovazione tecnologica, digitale e transizione verde',expenses:['Formazione','Consulenza'],partners:'Possibile progetto integrato',sectors:['Digitalizzazione','Sostenibilità'],keywords:['formazione','AI','cybersecurity','digital twin'],fit:['Utile per upskilling AI, automazione e cybersecurity','Territorio coerente'],risks:['Non finanzia impianti','Serve piano formativo dettagliato'],reason:'Candidatura diretta a basso rischio per rafforzare competenze strategiche interne.',next:'Costruire piano formativo MI su AI, digital twin, cybersecurity, automazione e data engineering.',url:'https://www.invitalia.it/incentivi-e-strumenti/sviluppo-competenze-specialistiche-delle-pmi'},
{id:'collabora',title:'Collabora & Innova – Edizione 2',decision:'PARTNER',priority:'B',source:'Regione Lombardia',territory:['Lombardia'],deadline:'2026-09-22',grant:'Contributo R&S',budget:'≥ 3,5 M€',beneficiaries:'Partenariati tra imprese e organismi di ricerca',what:'R&S collaborativa coerente con ecosistemi S3 Lombardia',expenses:['Personale R&S','Consulenza','Prototipi'],partners:'Partenariato obbligatorio',sectors:['Industria 4.0','Energia','Digitalizzazione'],keywords:['IoT','digital twin','S3','ricerca industriale'],fit:['Forte contenuto R&S','Buono per dimostratori industriali'],risks:['Attività agevolate in Lombardia','Budget minimo alto','Scadenza ravvicinata'],reason:'Per MI ha più senso entrare in un partenariato lombardo che impostare una candidatura autonoma.',next:'Cercare partner/capofila lombardo e verificare quota attività MI ammissibile.',url:'https://www.openinnovation.regione.lombardia.it/it/bandi-e-sperimentazioni/collabora-innova/collabora-innova-edizione-2'},
{id:'rafforza',title:'Rafforza&Innova',decision:'PARTNER',priority:'C',source:'Regione Lombardia',territory:['Lombardia'],deadline:'2027-03-31',grant:'Contributo trasferimento tecnologico',budget:'Progetto di innovazione',beneficiaries:'PMI lombarde secondo il bando',what:'Trasferimento tecnologico e introduzione di soluzioni innovative',expenses:['Consulenza','Ricerca contrattuale'],partners:'Collaborazione con OdR/soggetti qualificati',sectors:['Industria 4.0','Digitalizzazione'],keywords:['trasferimento tecnologico','IoT','innovazione'],fit:['Possibile ruolo MI come partner o fornitore tecnologico'],risks:['Territorialità lombarda','MI non appare beneficiario naturale'],reason:'Opportunità commerciale/tecnologica più che incentivo diretto per MI.',next:'Individuare PMI lombarde interessate a IoT, automazione o digital twin.',url:'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/ricerca-innovazione/ricerca-sviluppo-innovazione/rafforza-innova-RLF12025044783'},
{id:'irccs',title:'IRCCS – Ricerca & Trasferisci',decision:'PARTNER',priority:'C',fresh:true,source:'Regione Lombardia',territory:['Lombardia'],deadline:'2026-10-21',grant:'Contributo R&S',budget:'Progetti R&S sanitari',beneficiaries:'IRCCS lombardi',what:'Ricerca industriale e sviluppo sperimentale con trasferimento tecnologico sanitario',expenses:['Personale R&S','Consulenza','Prototipi'],partners:'Possibile fornitore/partner tecnico',sectors:['Elettronica','Digitalizzazione'],keywords:['sensoristica','IoT','digitale','sanità'],fit:['Possibile ruolo su sensoristica e sistemi digitali'],risks:['MI non beneficiario diretto','Ambito sanitario specialistico'],reason:'Non candidarsi direttamente: valutare solo ruolo tecnologico in un progetto guidato da IRCCS.',next:'Verificare contatti IRCCS e necessità di sensoristica/IoT/digitalizzazione.',url:'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/ricerca-innovazione/ricerca-sperimentazione-ambito-sanitario/irccs-ricerca-trasferisci-RLF12025045924'},
{id:'life',title:'LIFE Calls for proposals 2026',decision:'PARTNER',priority:'B',source:'CINEA',territory:['UE'],deadline:'2026-09-23',grant:'Co-finanziamento UE variabile',budget:'Dipende dalla call',beneficiaries:'Enti pubblici e privati secondo topic LIFE',what:'Ambiente, clima, economia circolare e clean energy transition',expenses:['Personale R&S','Consulenza','Prototipi','Efficienza energetica'],partners:'Dipende dal topic; forte dimensione europea',sectors:['Energia','Sostenibilità'],keywords:['clean energy','efficienza energetica','climate'],fit:['Buono per efficienza energetica e digitalizzazione energia'],risks:['Competizione europea','Proposta onerosa','Serve topic specifico'],reason:'Interessante soprattutto entrando in un consorzio europeo già in formazione.',next:'Filtrare topic LIFE coerenti e cercare consorzi/partner capofila.',url:'https://cinea.ec.europa.eu/life-calls-proposals-2026_en'}]

const score=(g:Grant)=>Math.min(100,35+(g.priority==='A'?25:g.priority==='B'?15:5)+Math.min(25,g.fit.length*8)+(g.territory.includes('Sicilia')?15:0))
const urgency=(g:Grant)=>{const d=Math.ceil((new Date(`${g.deadline}T23:59:59`).getTime()-Date.now())/86400000);return d<0?'Scaduto/da verificare':d<=15?`${d} gg · URGENTE`:d<=45?`${d} gg`:new Date(g.deadline).toLocaleDateString('it-IT')}

function App(){
 const [decision,setDecision]=useState<'all'|Decision>('all'); const [q,setQ]=useState(''); const [territory,setTerritory]=useState(''); const [expense,setExpense]=useState(''); const [priority,setPriority]=useState(''); const [selected,setSelected]=useState<Grant|null>(null); const [favorites,setFavorites]=useState<string[]>(()=>JSON.parse(localStorage.getItem('br-fav')||'[]')); const [favOnly,setFavOnly]=useState(false); const [newOnly,setNewOnly]=useState(false)
 const filtered=useMemo(()=>grants.filter(g=>(decision==='all'||g.decision===decision)&&(!favOnly||favorites.includes(g.id))&&(!newOnly||g.fresh)&&(!territory||g.territory.includes(territory))&&(!expense||g.expenses.includes(expense))&&(!priority||g.priority===priority)&&(g.title+' '+g.what+' '+g.keywords.join(' ')+' '+g.expenses.join(' ')).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>score(b)-score(a)),[decision,q,territory,expense,priority,favOnly,newOnly,favorites])
 const toggleFav=(id:string)=>{const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem('br-fav',JSON.stringify(next))}
 return <main className="wrap">
  <header className="top"><div><h1>Bandi Radar MI</h1><p>Decision support per bandi, R&S e investimenti — Release R3</p></div><div className="actions"><button className={favOnly?'activeBtn':''} onClick={()=>setFavOnly(!favOnly)}>★ Preferiti</button><button className={newOnly?'activeBtn':''} onClick={()=>setNewOnly(!newOnly)}>● Nuovi</button><a className="primary" href="#sources">Stato fonti</a></div></header>
  <section className="metrics">{[['Da candidare',grants.filter(g=>g.decision==='CANDIDARSI').length],['Partner',grants.filter(g=>g.decision==='PARTNER').length],['Investimenti',grants.filter(g=>g.decision==='INVESTIMENTO').length],['Nuovi',grants.filter(g=>g.fresh).length],['Fonti scansionate',`${sources.filter(s=>s.status==='scanned').length}/${sources.length}`]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><b>{v}</b></div>)}</section>
  <section className="panel"><div className="toolbar"><div><h2>Coda decisionale</h2><p>Prima capisci cosa fare; poi apri il dettaglio tecnico.</p></div><div className="tabs">{['all','CANDIDARSI','PARTNER','INVESTIMENTO','SCARTARE'].map(x=><button key={x} className={decision===x?'active':''} onClick={()=>setDecision(x as 'all'|Decision)}>{x==='all'?'Tutti':x}</button>)}</div></div>
   <div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca IoT, energia, cybersecurity, macchinari..."/><select value={territory} onChange={e=>setTerritory(e.target.value)}><option value="">Tutti i territori</option>{['Sicilia','Mezzogiorno','Italia','Lombardia','UE'].map(x=><option key={x}>{x}</option>)}</select><select value={expense} onChange={e=>setExpense(e.target.value)}><option value="">Qualsiasi spesa</option>{['Personale R&S','Macchinari e impianti','Software e licenze','Consulenza','Formazione','Prototipi','Efficienza energetica'].map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Qualsiasi priorità</option><option value="A">Priorità A</option><option value="B">Priorità B</option><option value="C">Priorità C</option></select></div>
   <div className="grid">{filtered.map(g=><article className="grant" key={g.id} onClick={()=>setSelected(g)}><div className="grantHead"><div className={`score ${score(g)>=80?'hi':'mid'}`}>{score(g)}</div><div><div><span className={`decision ${g.decision.toLowerCase()}`}>{g.decision}</span> <span className="priority">Priorità {g.priority}</span> {g.fresh&&<span className="fresh">NUOVO</span>}</div><h3>{g.title}</h3><small>{g.source} · {g.territory.join(' · ')} · {urgency(g)}</small></div><button className="star" onClick={e=>{e.stopPropagation();toggleFav(g.id)}}>{favorites.includes(g.id)?'★':'☆'}</button></div><div className="reason"><b>Decisione:</b> {g.reason}</div><div className="quick"><div><small>Finanzia</small><b>{g.what}</b></div><div><small>Dimensione</small><b>{g.budget}</b></div><div><small>Agevolazione</small><b>{g.grant}</b></div></div><div>{g.expenses.map(x=><span className="chip" key={x}>{x}</span>)}</div></article>)}</div>
  </section>
  <section className="panel" id="sources"><div className="toolbar"><div><h2>Stato scansioni</h2><p>Scansionata = controllata nell'ultimo ciclo. Pianificata = collector ancora da collegare.</p></div><span className="stamp">Ultimo ciclo: 24/08/2026 17:31</span></div><div className="sourceGrid">{sources.map(s=><div className="source" key={s.name}><div className="sourceHead"><b>{s.name}</b><span className={s.status}>{s.status==='scanned'?'Scansionata':'Pianificata'}</span></div><small>{s.scope} · ultimo controllo {s.last}</small><p>Rilevati <b>{s.found}</b> · nuovi <b>{s.fresh}</b></p><a href={s.url} target="_blank" rel="noreferrer">Fonte ufficiale ↗</a></div>)}</div></section>
  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className={`decision ${selected.decision.toLowerCase()}`}>{selected.decision}</span> <span className="priority">Priorità {selected.priority}</span><h2>{selected.title}</h2><p className="muted">{selected.source} · {selected.territory.join(' · ')} · {urgency(selected)}</p><div className="detailGrid"><div><small>Fit MI</small><b>{score(selected)}/100</b></div><div><small>Progetto</small><b>{selected.budget}</b></div><div><small>Agevolazione</small><b>{selected.grant}</b></div><div><small>Ruolo</small><b>{selected.decision}</b></div></div><section><h3>Decisione raccomandata</h3><p><b>{selected.reason}</b></p><p>{selected.next}</p></section><div className="columns"><div><section><h3>Di cosa si occupa</h3><p>{selected.what}</p></section><section><h3>Chi può partecipare</h3><p>{selected.beneficiaries}</p></section><section><h3>Spese finanziabili</h3>{selected.expenses.map(x=><span className="chip" key={x}>{x}</span>)}</section></div><div><section><h3>Perché interessa a MI</h3>{selected.fit.map(x=><div className="good" key={x}>✓ {x}</div>)}</section><section><h3>Attenzioni</h3>{selected.risks.map(x=><div className="warn" key={x}>! {x}</div>)}</section></div></div><section><h3>Partenariato</h3><p>{selected.partners}</p></section><section><h3>Link ufficiale</h3><div className="official">{selected.url}</div><p><a className="primary" href={selected.url} target="_blank" rel="noreferrer">Apri bando ufficiale ↗</a></p></section></div></div>}
 </main>
}
export default App
