import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'

type FunctionRow={id:string;name:string;owner:string;people:number;mission:string;systems:string}
type ProcessRow={id:string;name:string;functionId:string;owner:string;lead:number;touch:number;volume:number;pain:string}
type TaskRow={id:string;name:string;processId:string;frequency:number;minutes:number;people:number;cost:number;repeat:number;data:number;judgement:number;pain:string}
type Opportunity={id:string;title:string;source:string;time:number;repeat:number;automation:number;data:number;frequency:number;impact:number;risk:number}
type UseCase={id:string;title:string;owner:string;kpi:string;baseline:number;target:number;setup:number;opex:number;benefit:number;status:string}
type SurveyLog={id:string;form:string;submittedAt:string;summary:string}
type Milestone={id:string;title:string;phase:string;plannedStart:string;plannedEnd:string;actualStart:string;actualEnd:string;progress:number;status:string;owner:string;notes:string}
type Store={company:{name:string;sector:string;employees:number;sites:string;goal:string;programStart:string};functions:FunctionRow[];processes:ProcessRow[];tasks:TaskRow[];opportunities:Opportunity[];useCases:UseCase[];surveyLog:SurveyLog[];milestones:Milestone[]}

const iso=(d:Date)=>d.toISOString().slice(0,10)
const plus=(date:string,days:number)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return iso(d)}
const daysDiff=(a:string,b:string)=>Math.round((new Date(b+'T12:00:00').getTime()-new Date(a+'T12:00:00').getTime())/86400000)
const defaultStart=iso(new Date())
const makeMilestones=(s:string):Milestone[]=>[
 {id:'MS-01',title:'Kick-off e mandato',phase:'DISCOVER',plannedStart:s,plannedEnd:plus(s,2),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'AI Transformation Manager',notes:''},
 {id:'MS-02',title:'Organization Discovery / F01',phase:'DISCOVER',plannedStart:plus(s,2),plannedEnd:plus(s,10),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'AI Transformation Manager',notes:''},
 {id:'MS-03',title:'AI Maturity T0 / F02',phase:'ASSESS',plannedStart:plus(s,7),plannedEnd:plus(s,15),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'AI Transformation Manager',notes:''},
 {id:'MS-04',title:'Task Inventory / F03',phase:'MAP',plannedStart:plus(s,8),plannedEnd:plus(s,22),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'Process Owner / Staff',notes:''},
 {id:'MS-05',title:'Process Discovery / F04',phase:'MAP',plannedStart:plus(s,12),plannedEnd:plus(s,25),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'Process Owner',notes:''},
 {id:'MS-06',title:'Opportunity Map + Top 10',phase:'SCORE',plannedStart:plus(s,20),plannedEnd:plus(s,30),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'AI Transformation Manager',notes:''},
 {id:'MS-07',title:'Business case e selezione 3 PoC',phase:'VALUE',plannedStart:plus(s,30),plannedEnd:plus(s,45),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'Steering Committee',notes:''},
 {id:'MS-08',title:'PoC Wave 1 e misurazione',phase:'POC',plannedStart:plus(s,45),plannedEnd:plus(s,90),actualStart:'',actualEnd:'',progress:0,status:'PIANIFICATO',owner:'PoC Owner',notes:''}
]

const seed:Store={company:{name:'Meridionale Impianti',sector:'Impiantistica / Engineering',employees:0,sites:'',goal:'Ridurre inefficienze e aumentare produttività, qualità e capacità operativa',programStart:defaultStart},functions:[{id:'FUNC-001',name:'R&D / Innovazione',owner:'',people:0,mission:'Ricerca, sviluppo e innovazione',systems:'Microsoft 365'},{id:'FUNC-002',name:'Engineering',owner:'',people:0,mission:'Progettazione e documentazione tecnica',systems:'Microsoft 365 / software tecnici'},{id:'FUNC-003',name:'Project Management',owner:'',people:0,mission:'Pianificazione, coordinamento e controllo commesse',systems:'Microsoft 365'}],processes:[{id:'PROC-0001',name:'Scouting bandi e opportunità',functionId:'FUNC-001',owner:'',lead:8,touch:4,volume:8,pain:'Ricerca dispersiva e manuale'},{id:'PROC-0002',name:'Analisi documentazione tecnica',functionId:'FUNC-002',owner:'',lead:16,touch:8,volume:12,pain:'Ricerca requisiti e confronto revisioni'},{id:'PROC-0003',name:'Weekly project reporting',functionId:'FUNC-003',owner:'',lead:6,touch:3,volume:16,pain:'Raccolta manuale di informazioni'}],tasks:[{id:'TASK-0001',name:'Ricerca opportunità/bandi',processId:'PROC-0001',frequency:200,minutes:60,people:1,cost:35,repeat:5,data:4,judgement:3,pain:'Molte fonti e verifiche manuali'},{id:'TASK-0002',name:'Analisi capitolati e specifiche',processId:'PROC-0002',frequency:100,minutes:120,people:2,cost:40,repeat:4,data:4,judgement:4,pain:'Documenti lunghi e requisiti dispersi'},{id:'TASK-0003',name:'Preparazione report progetto',processId:'PROC-0003',frequency:50,minutes:180,people:2,cost:45,repeat:5,data:4,judgement:3,pain:'Dati distribuiti tra email, file e meeting'}],opportunities:[{id:'OPP-0001',title:'Tender/Bandi Intelligence',source:'TASK-0001',time:5,repeat:5,automation:5,data:4,frequency:5,impact:5,risk:2},{id:'OPP-0002',title:'Engineering Document Copilot',source:'TASK-0002',time:5,repeat:4,automation:4,data:4,frequency:4,impact:5,risk:4},{id:'OPP-0003',title:'Project Manager Copilot',source:'TASK-0003',time:5,repeat:5,automation:4,data:4,frequency:4,impact:5,risk:3}],useCases:[{id:'UC-001',title:'Tender/Bandi Intelligence',owner:'',kpi:'Ore ricerca / opportunità qualificate',baseline:60,target:20,setup:8000,opex:3000,benefit:26000,status:'ASSESS'},{id:'UC-002',title:'MI Knowledge Assistant',owner:'',kpi:'Tempo medio ricerca documenti',baseline:20,target:5,setup:12000,opex:5000,benefit:42000,status:'IDEA'},{id:'UC-003',title:'Project Manager Copilot',owner:'',kpi:'Ore reporting / mese',baseline:30,target:12,setup:10000,opex:4000,benefit:35000,status:'ASSESS'}],surveyLog:[],milestones:makeMilestones(defaultStart)}

const steps=[['Discover','Capire come è fatta l’azienda prima di proporre soluzioni.','Funzioni, responsabili e sistemi principali censiti.'],['Assess','Creare una baseline di maturità, dati e criticità.','Assessment T0 e pain point principali.'],['Map','Misurare dove si consumano tempo e capacità.','Processi e task con frequenza, tempi e owner.'],['Score','Trasformare problemi in opportunità confrontabili.','Opportunity Score calcolabile.'],['Business case','Concentrare risorse solo dove il valore è credibile.','KPI, target, costi, beneficio e rischio.'],['PoC','Dimostrare il risultato su dati reali.','Before/after, campione e GO/NO-GO.'],['Scale & Review','Industrializzare solo ciò che genera valore.','Owner, governance, monitoraggio e review 30/90/180 giorni.']]
const score=(o:Opportunity)=>Math.max(0,Math.round(((o.time*.25+o.repeat*.20+o.automation*.20+o.data*.15+o.frequency*.10+o.impact*.10)/5)*100-(o.risk-1)*5))
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
const dl=(name:string,type:string,body:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

export default function App(){
 const [data,setData]=useState<Store>(()=>{try{const x=JSON.parse(localStorage.getItem('aito-store')||'null');if(!x)return seed;const start=x.company?.programStart||defaultStart;return{...seed,...x,company:{...seed.company,...x.company,programStart:start},surveyLog:x.surveyLog||[],milestones:x.milestones||makeMilestones(start)}}catch{return seed}})
 const [tab,setTab]=useState('dashboard'),[phase,setPhase]=useState(0),[editing,setEditing]=useState(false),[notice,setNotice]=useState('')
 const fileRef=useRef<HTMLInputElement>(null)
 const [f01,setF01]=useState({name:'',owner:'',people:0,mission:'',systems:'',pain:''})
 const [f03,setF03]=useState({name:'',processId:'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''})
 useEffect(()=>localStorage.setItem('aito-store',JSON.stringify(data)),[data])
 const metrics=useMemo(()=>{const hours=data.tasks.reduce((s,t)=>s+t.frequency*t.minutes*t.people/60,0);const capacity=data.tasks.reduce((s,t)=>s+t.frequency*t.minutes*t.people/60*t.cost,0);const avg=data.opportunities.length?Math.round(data.opportunities.reduce((s,o)=>s+score(o),0)/data.opportunities.length):0;const benefit=data.useCases.reduce((s,u)=>s+u.benefit,0),invest=data.useCases.reduce((s,u)=>s+u.setup+u.opex,0);return{hours,capacity,avg,benefit,invest,roi:invest?Math.round((benefit-invest)/invest*100):0}},[data])
 const completion=Math.min(100,Math.round((data.functions.length>=5?20:data.functions.length*4)+(data.processes.length>=10?20:data.processes.length*2)+(data.tasks.length>=30?25:data.tasks.length*.83)+(data.opportunities.length>=10?20:data.opportunities.length*2)+(data.useCases.length>=3?15:data.useCases.length*5)))
 const missingOwners=data.functions.filter(f=>!f.owner).length+data.processes.filter(p=>!p.owner).length
 const planProgress=Math.round(data.milestones.reduce((s,m)=>s+m.progress,0)/Math.max(1,data.milestones.length))
 const today=iso(new Date())
 const delayed=data.milestones.filter(m=>m.progress<100&&m.plannedEnd<today).length
 const snapshot=()=>({format:'AI_TRANSFORMATION_OS_BACKUP',version:'0.3.0',exported_at:new Date().toISOString(),data,derived:{metrics,completion,missingOwners,planProgress,delayed,opportunities:data.opportunities.map(o=>({...o,opportunity_score:score(o)}))}})
 const exportBackup=()=>{dl(`ai-transformation-os-backup-${today}.json`,'application/json',JSON.stringify(snapshot(),null,2));setNotice('Backup JSON esportato con successo.')}
 const importBackup=(file:File)=>{const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));const imported=p.data||p;if(!imported.company||!Array.isArray(imported.functions)||!Array.isArray(imported.processes)||!Array.isArray(imported.tasks))throw new Error('schema');const start=imported.company.programStart||defaultStart;setData({...seed,...imported,company:{...seed.company,...imported.company,programStart:start},surveyLog:imported.surveyLog||[],milestones:imported.milestones||makeMilestones(start)});setNotice('Backup importato. Tutti i dati sono stati ripristinati nel browser.')}catch{setNotice('Importazione fallita: il file non è un backup valido.')}};r.readAsText(file)}
 const companyReport=()=>{const s=snapshot();const md=`# Company Intelligence Report\n\nSnapshot: ${s.exported_at}\n\n## Executive snapshot\n- Azienda: ${data.company.name}\n- Programma avviato: ${data.company.programStart}\n- Avanzamento roadmap: ${planProgress}%\n- Milestone in ritardo: ${delayed}\n- Funzioni: ${data.functions.length}\n- Processi: ${data.processes.length}\n- Task: ${data.tasks.length}\n- Ore baseline: ${Math.round(metrics.hours)} h/anno\n- Capacity value: ${money(metrics.capacity)}\n- Opportunità: ${data.opportunities.length}\n- Opportunity score medio: ${metrics.avg}/100\n- Use case: ${data.useCases.length}\n- Beneficio annuo portfolio: ${money(metrics.benefit)}\n- ROI indicativo: ${metrics.roi}%\n- Completezza discovery: ${completion}%\n\n## Roadmap\n${data.milestones.map(m=>`- ${m.id} ${m.title} | ${m.plannedStart}→${m.plannedEnd} | ${m.progress}% | ${m.status}`).join('\n')}\n\n## Functions\n${data.functions.map(f=>`- ${f.id} ${f.name} | owner ${f.owner||'MANCANTE'} | persone ${f.people} | ${f.systems}`).join('\n')}\n\n## Processes\n${data.processes.map(p=>`- ${p.id} ${p.name} | lead ${p.lead}h | touch ${p.touch}h | ${p.pain}`).join('\n')}\n\n## Tasks\n${data.tasks.map(t=>`- ${t.id} ${t.name} | ${Math.round(t.frequency*t.minutes*t.people/60)} h/a | ${t.pain}`).join('\n')}\n\n## Opportunities\n${[...data.opportunities].sort((a,b)=>score(b)-score(a)).map(o=>`- ${o.id} ${o.title}: ${score(o)}/100`).join('\n')}\n\n## Data gaps\n- Owner mancanti: ${missingOwners}\n`;dl('company-intelligence-report.md','text/markdown',md);dl('company-snapshot.json','application/json',JSON.stringify(s,null,2));setTimeout(()=>window.print(),250)}
 const addFunction=()=>setData(d=>({...d,functions:[...d.functions,{id:`FUNC-${String(d.functions.length+1).padStart(3,'0')}`,name:'Nuova funzione',owner:'',people:0,mission:'',systems:''}]}))
 const addProcess=()=>setData(d=>({...d,processes:[...d.processes,{id:`PROC-${String(d.processes.length+1).padStart(4,'0')}`,name:'Nuovo processo',functionId:d.functions[0]?.id||'',owner:'',lead:0,touch:0,volume:0,pain:''}]}))
 const addTask=()=>setData(d=>({...d,tasks:[...d.tasks,{id:`TASK-${String(d.tasks.length+1).padStart(4,'0')}`,name:'Nuovo task',processId:d.processes[0]?.id||'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''}]}))
 const patch=(kind:'functions'|'processes'|'tasks',i:number,key:string,v:string|number)=>setData(d=>({...d,[kind]:(d[kind] as any[]).map((x,j)=>j===i?{...x,[key]:v}:x)}))
 const patchMS=(i:number,key:keyof Milestone,v:string|number)=>setData(d=>({...d,milestones:d.milestones.map((m,j)=>j===i?{...m,[key]:v}:m)}))
 const changeStart=(v:string)=>setData(d=>({...d,company:{...d.company,programStart:v},milestones:makeMilestones(v)}))
 const submitF01=()=>{if(!f01.name.trim())return;const id=`FUNC-${String(data.functions.length+1).padStart(3,'0')}`;setData(d=>({...d,functions:[...d.functions,{id,name:f01.name,owner:f01.owner,people:+f01.people,mission:f01.mission,systems:f01.systems}],surveyLog:[...d.surveyLog,{id:`FORM-${Date.now()}`,form:'F01 Organization Discovery',submittedAt:new Date().toISOString(),summary:`${f01.name} — ${f01.pain}`}]}));setF01({name:'',owner:'',people:0,mission:'',systems:'',pain:''});setNotice('F01 acquisito: funzione aggiunta automaticamente.')}
 const submitF03=()=>{if(!f03.name.trim()||!f03.processId)return;const id=`TASK-${String(data.tasks.length+1).padStart(4,'0')}`;setData(d=>({...d,tasks:[...d.tasks,{id,name:f03.name,processId:f03.processId,frequency:+f03.frequency,minutes:+f03.minutes,people:+f03.people,cost:+f03.cost,repeat:+f03.repeat,data:+f03.data,judgement:+f03.judgement,pain:f03.pain}],surveyLog:[...d.surveyLog,{id:`FORM-${Date.now()}`,form:'F03 Task & Productivity',submittedAt:new Date().toISOString(),summary:f03.name}]}));setF03({name:'',processId:'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''});setNotice('F03 acquisito: task aggiunto automaticamente.')}
 const nav=[['dashboard','Dashboard'],['calendar','Calendario'],['company','Azienda'],['functions','Funzioni'],['processes','Processi'],['tasks','Task'],['surveys','Questionari'],['opportunities','Opportunità'],['usecases','Use case'],['data','Dati & Backup'],['report','Report']]
 return <div className="app"><aside><div className="brand"><span>AI</span><div>Transformation<br/><b>OS</b></div></div><div className="company-mini">{data.company.name}<small>Single-company workspace</small></div><nav>{nav.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><div className="side-foot"><b>{completion}%</b><span>Discovery completeness</span><div className="progress"><i style={{width:`${completion}%`}}/></div></div></aside><main><header><div><small>AI TRANSFORMATION PROGRAM</small><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="header-actions"><button className="ghost" onClick={()=>setEditing(!editing)}>{editing?'Fine modifica':'Modifica dati'}</button><button className="primary" onClick={companyReport}>Genera report azienda</button></div></header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}<section className="guide"><div><span className="eyebrow">FASE {phase+1} · {steps[phase][0].toUpperCase()}</span><h2>Cosa devi fare adesso</h2><p>{steps[phase][2]}</p></div><div className="guide-why"><b>Perché</b><p>{steps[phase][1]}</p></div><div className="phase-controls"><button disabled={phase===0} onClick={()=>setPhase(p=>p-1)}>←</button><strong>{phase+1}/{steps.length}</strong><button disabled={phase===steps.length-1} onClick={()=>setPhase(p=>p+1)}>→</button></div></section>
 {tab==='dashboard'&&<><div className="cards"><Metric label="Funzioni" value={data.functions.length}/><Metric label="Processi" value={data.processes.length}/><Metric label="Task" value={data.tasks.length}/><Metric label="Ore baseline" value={`${Math.round(metrics.hours)} h/a`}/><Metric label="Roadmap" value={`${planProgress}%`}/><Metric label="Milestone ritardo" value={delayed}/></div><div className="grid2"><Panel title="Azioni prioritarie"><Action done={data.functions.length>=5} title="Completa la mappa delle funzioni" detail={`${data.functions.length}/5 minimo iniziale`}/><Action done={data.processes.length>=10} title="Mappa i processi prioritari" detail={`${data.processes.length}/10`}/><Action done={data.tasks.length>=30} title="Raccogli i task reali" detail={`${data.tasks.length}/30`}/><Action done={data.functions.every(f=>f.owner)} title="Assegna i responsabili" detail={`${data.functions.filter(f=>!f.owner).length} owner mancanti`}/></Panel><Panel title="Top opportunità">{[...data.opportunities].sort((a,b)=>score(b)-score(a)).slice(0,5).map(o=><div className="rank" key={o.id}><div><b>{o.title}</b><small>{o.source}</small></div><strong>{score(o)}</strong></div>)}</Panel></div></>}
 {tab==='calendar'&&<><div className="calendar-head"><div><span>Data inizio programma</span><input type="date" value={data.company.programStart} onChange={e=>changeStart(e.target.value)}/><small>Modificando la data, il piano iniziale viene ricalcolato sui 90 giorni.</small></div><Metric label="Avanzamento medio" value={`${planProgress}%`}/><Metric label="In ritardo" value={delayed}/></div><div className="table-wrap"><table><thead><tr>{['ID','Milestone','Fase','Piano','Reale','Progress','Scostamento','Stato','Owner'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.milestones.map((m,i)=>{const variance=m.actualEnd?daysDiff(m.plannedEnd,m.actualEnd):(m.progress<100&&m.plannedEnd<today?daysDiff(m.plannedEnd,today):0);return <tr key={m.id}><td>{m.id}</td><td><b>{m.title}</b></td><td>{m.phase}</td><td>{m.plannedStart}<br/>{m.plannedEnd}</td><td><input className="cell-edit" type="date" value={m.actualStart} onChange={e=>patchMS(i,'actualStart',e.target.value)}/><input className="cell-edit" type="date" value={m.actualEnd} onChange={e=>patchMS(i,'actualEnd',e.target.value)}/></td><td><input className="cell-edit" type="number" min="0" max="100" value={m.progress} onChange={e=>patchMS(i,'progress',+e.target.value)}/>%</td><td className={variance>0?'late':''}>{variance>0?`+${variance} gg`:variance<0?`${variance} gg`:'0 gg'}</td><td><select className="cell-edit" value={m.status} onChange={e=>patchMS(i,'status',e.target.value)}><option>PIANIFICATO</option><option>IN CORSO</option><option>COMPLETATO</option><option>IN RITARDO</option><option>BLOCCATO</option></select></td><td><input className="cell-edit" value={m.owner} onChange={e=>patchMS(i,'owner',e.target.value)}/></td></tr>})}</tbody></table></div></>}
 {tab==='company'&&<Panel title="Profilo azienda"><div className="form-grid">{Object.entries(data.company).map(([k,v])=><label key={k}>{k}<input disabled={!editing||k==='programStart'} value={v as any} type={k==='employees'?'number':k==='programStart'?'date':'text'} onChange={e=>setData(d=>({...d,company:{...d.company,[k]:k==='employees'?+e.target.value:e.target.value}}))}/></label>)}</div></Panel>}
 {tab==='functions'&&<><Toolbar title="Mappa funzionale" text="Censisci tutte le funzioni e assegna un owner." add={addFunction}/><Table headers={['ID','Funzione','Responsabile','Persone','Missione','Sistemi']} rows={data.functions.map((f,i)=>[f.id,<Edit v={f.name} enabled={editing} set={v=>patch('functions',i,'name',v)}/>,<Edit v={f.owner} enabled={editing} set={v=>patch('functions',i,'owner',v)}/>,<Edit v={f.people} enabled={editing} set={v=>patch('functions',i,'people',+v)} type="number"/>,<Edit v={f.mission} enabled={editing} set={v=>patch('functions',i,'mission',v)}/>,<Edit v={f.systems} enabled={editing} set={v=>patch('functions',i,'systems',v)}/>])}/></>}
 {tab==='processes'&&<><Toolbar title="Process mapping" text="Misura lead time e touch time: la differenza evidenzia attese e colli di bottiglia." add={addProcess}/><Table headers={['ID','Processo','Funzione','Owner','Lead h','Touch h','Vol/mese','Pain point']} rows={data.processes.map((p,i)=>[p.id,<Edit v={p.name} enabled={editing} set={v=>patch('processes',i,'name',v)}/>,data.functions.find(f=>f.id===p.functionId)?.name||p.functionId,<Edit v={p.owner} enabled={editing} set={v=>patch('processes',i,'owner',v)}/>,<Edit v={p.lead} enabled={editing} set={v=>patch('processes',i,'lead',+v)} type="number"/>,<Edit v={p.touch} enabled={editing} set={v=>patch('processes',i,'touch',+v)} type="number"/>,<Edit v={p.volume} enabled={editing} set={v=>patch('processes',i,'volume',+v)} type="number"/>,<Edit v={p.pain} enabled={editing} set={v=>patch('processes',i,'pain',v)}/>])}/></>}
 {tab==='tasks'&&<><Toolbar title="Task inventory" text="Una riga = una attività. Frequenza × minuti × persone produce la baseline annua." add={addTask}/><Table headers={['ID','Task','Processo','Freq/a','Min','Persone','€/h','Ore/a','Pain']} rows={data.tasks.map((t,i)=>[t.id,<Edit v={t.name} enabled={editing} set={v=>patch('tasks',i,'name',v)}/>,data.processes.find(p=>p.id===t.processId)?.name||t.processId,<Edit v={t.frequency} enabled={editing} set={v=>patch('tasks',i,'frequency',+v)} type="number"/>,<Edit v={t.minutes} enabled={editing} set={v=>patch('tasks',i,'minutes',+v)} type="number"/>,<Edit v={t.people} enabled={editing} set={v=>patch('tasks',i,'people',+v)} type="number"/>,<Edit v={t.cost} enabled={editing} set={v=>patch('tasks',i,'cost',+v)} type="number"/>,Math.round(t.frequency*t.minutes*t.people/60),<Edit v={t.pain} enabled={editing} set={v=>patch('tasks',i,'pain',v)}/>])}/></>}
 {tab==='surveys'&&<><div className="survey-access"><h2>Come accedono i dipendenti</h2><p><b>Modalità attuale (locale):</b> i questionari integrati vengono salvati nel localStorage del browser in cui sono compilati. È adatta a test/interviste svolte sul tuo dispositivo, ma non ancora a raccolta distribuita.</p><p><b>Modalità centrale:</b> è in preparazione un archivio Postgres con link univoci per F01/F02/F03/F04. Il dipendente aprirà solo il questionario, senza vedere il gestionale; la risposta confluirà direttamente nell’archivio centrale e nel registro.</p></div><div className="grid2"><Survey title="F01 — Organization Discovery" onSubmit={submitF01}><label>Funzione<input value={f01.name} onChange={e=>setF01({...f01,name:e.target.value})}/></label><label>Responsabile<input value={f01.owner} onChange={e=>setF01({...f01,owner:e.target.value})}/></label><label>Persone<input type="number" value={f01.people} onChange={e=>setF01({...f01,people:+e.target.value})}/></label><label>Missione<input value={f01.mission} onChange={e=>setF01({...f01,mission:e.target.value})}/></label><label>Sistemi<input value={f01.systems} onChange={e=>setF01({...f01,systems:e.target.value})}/></label><label>Pain point<textarea value={f01.pain} onChange={e=>setF01({...f01,pain:e.target.value})}/></label></Survey><Survey title="F03 — Task & Productivity" onSubmit={submitF03}><label>Task<input value={f03.name} onChange={e=>setF03({...f03,name:e.target.value})}/></label><label>Processo<select value={f03.processId} onChange={e=>setF03({...f03,processId:e.target.value})}><option value="">Seleziona</option>{data.processes.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Frequenza annua<input type="number" value={f03.frequency} onChange={e=>setF03({...f03,frequency:+e.target.value})}/></label><label>Minuti<input type="number" value={f03.minutes} onChange={e=>setF03({...f03,minutes:+e.target.value})}/></label><label>Persone<input type="number" value={f03.people} onChange={e=>setF03({...f03,people:+e.target.value})}/></label><label>Pain point<textarea value={f03.pain} onChange={e=>setF03({...f03,pain:e.target.value})}/></label></Survey></div><Panel title="Registro questionari">{data.surveyLog.length?data.surveyLog.slice().reverse().map(x=><div className="rank" key={x.id}><div><b>{x.form}</b><small>{new Date(x.submittedAt).toLocaleString('it-IT')} · {x.summary}</small></div></div>):<p>Nessuna compilazione registrata.</p>}</Panel></>}
 {tab==='opportunities'&&<Table headers={['ID','Opportunità','Fonte','Score','Rischio']} rows={[...data.opportunities].sort((a,b)=>score(b)-score(a)).map(o=>[o.id,o.title,o.source,<b>{score(o)}/100</b>,o.risk])}/>} 
 {tab==='usecases'&&<div className="kanban">{['IDEA','ASSESS','POC','PRODUCTION'].map(s=><div className="lane" key={s}><h3>{s}</h3>{data.useCases.filter(u=>u.status===s).map(u=><div className="uc" key={u.id}><b>{u.title}</b><span>{u.kpi}</span><div><em>{money(u.setup+u.opex)}</em><strong>{money(u.benefit)}</strong></div></div>)}</div>)}</div>}
 {tab==='data'&&<div className="grid2"><Panel title="Esporta backup JSON"><p>Scarica l’intero workspace, incluse roadmap e risposte raccolte, per trasferirlo su un altro browser.</p><button className="primary" onClick={exportBackup}>Esporta tutti i dati</button></Panel><Panel title="Importa backup JSON"><p>Ripristina un backup precedente. L’importazione sostituisce i dati correnti del browser.</p><input ref={fileRef} hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importBackup(e.target.files[0])}/><button className="ghost" onClick={()=>fileRef.current?.click()}>Importa JSON</button></Panel></div>}
 {tab==='report'&&<div className="report-hero"><div><span className="eyebrow">COMPANY INTELLIGENCE REPORT</span><h2>Una fotografia completa dell’azienda</h2><p>Include roadmap pianificata/reale, funzioni, processi, task, pain point, opportunità, use case, KPI e gap informativi.</p><button className="primary big" onClick={companyReport}>Genera report completo</button></div><div className="report-list"><b>Output simultanei</b><span>PDF / stampa</span><span>Markdown AI-ready</span><span>JSON strutturato</span><span>Roadmap e scostamenti</span></div></div>}
 </main></div>
}

function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:any}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Action({done,title,detail}:{done:boolean;title:string;detail:string}){return <div className={`action ${done?'done':''}`}><i>{done?'✓':'!'}</i><div><b>{title}</b><small>{detail}</small></div></div>}
function Toolbar({title,text,add}:{title:string;text:string;add:()=>void}){return <div className="toolbar"><div><h2>{title}</h2><p>{text}</p></div><button className="primary" onClick={add}>+ Aggiungi</button></div>}
function Edit({v,set,enabled,type='text'}:{v:string|number;set:(v:string)=>void;enabled:boolean;type?:string}){return enabled?<input className="cell-edit" type={type} value={v} onChange={e=>set(e.target.value)}/>:<span className={!v?'missing':''}>{v||'Mancante'}</span>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Survey({title,onSubmit,children}:{title:string;onSubmit:()=>void;children:any}){return <section className="panel survey"><h3>{title}</h3><div className="survey-fields">{children}</div><button className="primary" onClick={onSubmit}>Registra risposta</button></section>}
