import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'

type FunctionRow={id:string;name:string;owner:string;people:number;mission:string;systems:string}
type ProcessRow={id:string;name:string;functionId:string;owner:string;lead:number;touch:number;volume:number;pain:string}
type TaskRow={id:string;name:string;processId:string;frequency:number;minutes:number;people:number;cost:number;repeat:number;data:number;judgement:number;pain:string}
type Opportunity={id:string;title:string;source:string;time:number;repeat:number;automation:number;data:number;frequency:number;impact:number;risk:number}
type UseCase={id:string;title:string;owner:string;kpi:string;baseline:number;target:number;setup:number;opex:number;benefit:number;status:string}
type SurveyLog={id:string;form:string;submittedAt:string;summary:string}
type Store={company:{name:string;sector:string;employees:number;sites:string;goal:string};functions:FunctionRow[];processes:ProcessRow[];tasks:TaskRow[];opportunities:Opportunity[];useCases:UseCase[];surveyLog:SurveyLog[]}

const seed:Store={company:{name:'Meridionale Impianti',sector:'Impiantistica / Engineering',employees:0,sites:'',goal:'Ridurre inefficienze e aumentare produttività, qualità e capacità operativa'},functions:[{id:'FUNC-001',name:'R&D / Innovazione',owner:'',people:0,mission:'Ricerca, sviluppo e innovazione',systems:'Microsoft 365'},{id:'FUNC-002',name:'Engineering',owner:'',people:0,mission:'Progettazione e documentazione tecnica',systems:'Microsoft 365 / software tecnici'},{id:'FUNC-003',name:'Project Management',owner:'',people:0,mission:'Pianificazione, coordinamento e controllo commesse',systems:'Microsoft 365'}],processes:[{id:'PROC-0001',name:'Scouting bandi e opportunità',functionId:'FUNC-001',owner:'',lead:8,touch:4,volume:8,pain:'Ricerca dispersiva e manuale'},{id:'PROC-0002',name:'Analisi documentazione tecnica',functionId:'FUNC-002',owner:'',lead:16,touch:8,volume:12,pain:'Ricerca requisiti e confronto revisioni'},{id:'PROC-0003',name:'Weekly project reporting',functionId:'FUNC-003',owner:'',lead:6,touch:3,volume:16,pain:'Raccolta manuale di informazioni'}],tasks:[{id:'TASK-0001',name:'Ricerca opportunità/bandi',processId:'PROC-0001',frequency:200,minutes:60,people:1,cost:35,repeat:5,data:4,judgement:3,pain:'Molte fonti e verifiche manuali'},{id:'TASK-0002',name:'Analisi capitolati e specifiche',processId:'PROC-0002',frequency:100,minutes:120,people:2,cost:40,repeat:4,data:4,judgement:4,pain:'Documenti lunghi e requisiti dispersi'},{id:'TASK-0003',name:'Preparazione report progetto',processId:'PROC-0003',frequency:50,minutes:180,people:2,cost:45,repeat:5,data:4,judgement:3,pain:'Dati distribuiti tra email, file e meeting'}],opportunities:[{id:'OPP-0001',title:'Tender/Bandi Intelligence',source:'TASK-0001',time:5,repeat:5,automation:5,data:4,frequency:5,impact:5,risk:2},{id:'OPP-0002',title:'Engineering Document Copilot',source:'TASK-0002',time:5,repeat:4,automation:4,data:4,frequency:4,impact:5,risk:4},{id:'OPP-0003',title:'Project Manager Copilot',source:'TASK-0003',time:5,repeat:5,automation:4,data:4,frequency:4,impact:5,risk:3}],useCases:[{id:'UC-001',title:'Tender/Bandi Intelligence',owner:'',kpi:'Ore ricerca / opportunità qualificate',baseline:60,target:20,setup:8000,opex:3000,benefit:26000,status:'ASSESS'},{id:'UC-002',title:'MI Knowledge Assistant',owner:'',kpi:'Tempo medio ricerca documenti',baseline:20,target:5,setup:12000,opex:5000,benefit:42000,status:'IDEA'},{id:'UC-003',title:'Project Manager Copilot',owner:'',kpi:'Ore reporting / mese',baseline:30,target:12,setup:10000,opex:4000,benefit:35000,status:'ASSESS'}],surveyLog:[]}

const steps=[['Discover','Capire come è fatta l’azienda prima di proporre soluzioni.','Funzioni, responsabili e sistemi principali censiti.'],['Assess','Creare una baseline di maturità, dati e criticità.','Assessment T0 e pain point principali.'],['Map','Misurare dove si consumano tempo e capacità.','Processi e task con frequenza, tempi e owner.'],['Score','Trasformare problemi in opportunità confrontabili.','Opportunity Score calcolabile.'],['Business case','Concentrare risorse solo dove il valore è credibile.','KPI, target, costi, beneficio e rischio.'],['PoC','Dimostrare il risultato su dati reali.','Before/after, campione e GO/NO-GO.'],['Scale & Review','Industrializzare solo ciò che genera valore.','Owner, governance, monitoraggio e review 30/90/180 giorni.']]
const score=(o:Opportunity)=>Math.max(0,Math.round(((o.time*.25+o.repeat*.20+o.automation*.20+o.data*.15+o.frequency*.10+o.impact*.10)/5)*100-(o.risk-1)*5))
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
const dl=(name:string,type:string,body:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

export default function App(){
 const [data,setData]=useState<Store>(()=>{try{const x=JSON.parse(localStorage.getItem('aito-store')||'null');return x?{...seed,...x,surveyLog:x.surveyLog||[]}:seed}catch{return seed}})
 const [tab,setTab]=useState('dashboard'),[phase,setPhase]=useState(0),[editing,setEditing]=useState(false),[notice,setNotice]=useState('')
 const fileRef=useRef<HTMLInputElement>(null)
 const [f01,setF01]=useState({name:'',owner:'',people:0,mission:'',systems:'',pain:''})
 const [f03,setF03]=useState({name:'',processId:'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''})
 useEffect(()=>localStorage.setItem('aito-store',JSON.stringify(data)),[data])
 const metrics=useMemo(()=>{const hours=data.tasks.reduce((s,t)=>s+t.frequency*t.minutes*t.people/60,0);const capacity=data.tasks.reduce((s,t)=>s+t.frequency*t.minutes*t.people/60*t.cost,0);const avg=data.opportunities.length?Math.round(data.opportunities.reduce((s,o)=>s+score(o),0)/data.opportunities.length):0;const benefit=data.useCases.reduce((s,u)=>s+u.benefit,0),invest=data.useCases.reduce((s,u)=>s+u.setup+u.opex,0);return{hours,capacity,avg,benefit,invest,roi:invest?Math.round((benefit-invest)/invest*100):0}},[data])
 const completion=Math.min(100,Math.round((data.functions.length>=5?20:data.functions.length*4)+(data.processes.length>=10?20:data.processes.length*2)+(data.tasks.length>=30?25:data.tasks.length*.83)+(data.opportunities.length>=10?20:data.opportunities.length*2)+(data.useCases.length>=3?15:data.useCases.length*5)))
 const missingOwners=data.functions.filter(f=>!f.owner).length+data.processes.filter(p=>!p.owner).length
 const snapshot=()=>({format:'AI_TRANSFORMATION_OS_BACKUP',version:'0.2.0',exported_at:new Date().toISOString(),data,derived:{metrics,completion,missingOwners,opportunities:data.opportunities.map(o=>({...o,opportunity_score:score(o)}))}})
 const exportBackup=()=>{dl(`ai-transformation-os-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(snapshot(),null,2));setNotice('Backup JSON esportato con successo.')}
 const importBackup=(file:File)=>{const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));const imported=p.data||p;if(!imported.company||!Array.isArray(imported.functions)||!Array.isArray(imported.processes)||!Array.isArray(imported.tasks))throw new Error('schema');setData({...seed,...imported,surveyLog:imported.surveyLog||[]});setNotice('Backup importato. Tutti i dati sono stati ripristinati nel browser.')}catch{setNotice('Importazione fallita: il file non è un backup valido.')}};r.readAsText(file)}
 const companyReport=()=>{const s=snapshot();const md=`# Company Intelligence Report\n\nSnapshot: ${s.exported_at}\n\n## Executive snapshot\n- Azienda: ${data.company.name}\n- Funzioni: ${data.functions.length}\n- Processi: ${data.processes.length}\n- Task: ${data.tasks.length}\n- Ore baseline: ${Math.round(metrics.hours)} h/anno\n- Capacity value: ${money(metrics.capacity)}\n- Opportunità: ${data.opportunities.length}\n- Opportunity score medio: ${metrics.avg}/100\n- Use case: ${data.useCases.length}\n- Beneficio annuo portfolio: ${money(metrics.benefit)}\n- ROI indicativo: ${metrics.roi}%\n- Completezza: ${completion}%\n\n## Functions\n${data.functions.map(f=>`- ${f.id} ${f.name} | owner ${f.owner||'MANCANTE'} | persone ${f.people} | ${f.systems}`).join('\n')}\n\n## Processes\n${data.processes.map(p=>`- ${p.id} ${p.name} | lead ${p.lead}h | touch ${p.touch}h | ${p.pain}`).join('\n')}\n\n## Tasks\n${data.tasks.map(t=>`- ${t.id} ${t.name} | ${Math.round(t.frequency*t.minutes*t.people/60)} h/a | ${t.pain}`).join('\n')}\n\n## Opportunities\n${[...data.opportunities].sort((a,b)=>score(b)-score(a)).map(o=>`- ${o.id} ${o.title}: ${score(o)}/100`).join('\n')}\n\n## Data gaps\n- Owner mancanti: ${missingOwners}\n` ;dl('company-intelligence-report.md','text/markdown',md);dl('company-snapshot.json','application/json',JSON.stringify(s,null,2));setTimeout(()=>window.print(),250)}
 const addFunction=()=>setData(d=>({...d,functions:[...d.functions,{id:`FUNC-${String(d.functions.length+1).padStart(3,'0')}`,name:'Nuova funzione',owner:'',people:0,mission:'',systems:''}]}))
 const addProcess=()=>setData(d=>({...d,processes:[...d.processes,{id:`PROC-${String(d.processes.length+1).padStart(4,'0')}`,name:'Nuovo processo',functionId:d.functions[0]?.id||'',owner:'',lead:0,touch:0,volume:0,pain:''}]}))
 const addTask=()=>setData(d=>({...d,tasks:[...d.tasks,{id:`TASK-${String(d.tasks.length+1).padStart(4,'0')}`,name:'Nuovo task',processId:d.processes[0]?.id||'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''}]}))
 const patch=(kind:'functions'|'processes'|'tasks',i:number,key:string,v:string|number)=>setData(d=>({...d,[kind]:(d[kind] as any[]).map((x,j)=>j===i?{...x,[key]:v}:x)}))
 const submitF01=()=>{if(!f01.name.trim())return;const id=`FUNC-${String(data.functions.length+1).padStart(3,'0')}`;setData(d=>({...d,functions:[...d.functions,{id,name:f01.name,owner:f01.owner,people:+f01.people,mission:f01.mission,systems:f01.systems}],surveyLog:[...d.surveyLog,{id:`FORM-${Date.now()}`,form:'F01 Organization Discovery',submittedAt:new Date().toISOString(),summary:`${f01.name} — ${f01.pain}`}]}));setF01({name:'',owner:'',people:0,mission:'',systems:'',pain:''});setNotice('F01 acquisito: funzione aggiunta automaticamente.')}
 const submitF03=()=>{if(!f03.name.trim()||!f03.processId)return;const id=`TASK-${String(data.tasks.length+1).padStart(4,'0')}`;setData(d=>({...d,tasks:[...d.tasks,{id,name:f03.name,processId:f03.processId,frequency:+f03.frequency,minutes:+f03.minutes,people:+f03.people,cost:+f03.cost,repeat:+f03.repeat,data:+f03.data,judgement:+f03.judgement,pain:f03.pain}],surveyLog:[...d.surveyLog,{id:`FORM-${Date.now()}`,form:'F03 Task & Productivity',submittedAt:new Date().toISOString(),summary:f03.name}]}));setF03({name:'',processId:'',frequency:0,minutes:0,people:1,cost:35,repeat:3,data:3,judgement:3,pain:''});setNotice('F03 acquisito: task aggiunto automaticamente.')}
 const nav=[['dashboard','Dashboard'],['company','Azienda'],['functions','Funzioni'],['processes','Processi'],['tasks','Task'],['surveys','Questionari'],['opportunities','Opportunità'],['usecases','Use case'],['data','Dati & Backup'],['report','Report']]
 return <div className="app"><aside><div className="brand"><span>AI</span><div>Transformation<br/><b>OS</b></div></div><div className="company-mini">{data.company.name}<small>Single-company workspace</small></div><nav>{nav.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><div className="side-foot"><b>{completion}%</b><span>Discovery completeness</span><div className="progress"><i style={{width:`${completion}%`}}/></div></div></aside><main><header><div><small>AI TRANSFORMATION PROGRAM</small><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="header-actions"><button className="ghost" onClick={()=>setEditing(!editing)}>{editing?'Fine modifica':'Modifica dati'}</button><button className="primary" onClick={companyReport}>Genera report azienda</button></div></header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}<section className="guide"><div><span className="eyebrow">FASE {phase+1} · {steps[phase][0].toUpperCase()}</span><h2>Cosa devi fare adesso</h2><p>{steps[phase][2]}</p></div><div className="guide-why"><b>Perché</b><p>{steps[phase][1]}</p></div><div className="phase-controls"><button disabled={phase===0} onClick={()=>setPhase(p=>p-1)}>←</button><strong>{phase+1}/{steps.length}</strong><button disabled={phase===steps.length-1} onClick={()=>setPhase(p=>p+1)}>→</button></div></section>
 {tab==='dashboard'&&<><div className="cards"><Metric label="Funzioni" value={data.functions.length}/><Metric label="Processi" value={data.processes.length}/><Metric label="Task" value={data.tasks.length}/><Metric label="Ore baseline" value={`${Math.round(metrics.hours)} h/a`}/><Metric label="Capacity value" value={money(metrics.capacity)}/><Metric label="Opportunity score" value={`${metrics.avg}/100`}/></div><div className="grid2"><Panel title="Azioni prioritarie"><Action done={data.functions.length>=5} title="Completa la mappa delle funzioni" detail={`${data.functions.length}/5 minimo iniziale`}/><Action done={data.processes.length>=10} title="Mappa i processi prioritari" detail={`${data.processes.length}/10`}/><Action done={data.tasks.length>=30} title="Raccogli i task reali" detail={`${data.tasks.length}/30`}/><Action done={missingOwners===0} title="Assegna i responsabili" detail={`${missingOwners} owner mancanti`}/></Panel><Panel title="Top opportunità">{[...data.opportunities].sort((a,b)=>score(b)-score(a)).slice(0,5).map(o=><div className="rank" key={o.id}><div><b>{o.title}</b><small>{o.source}</small></div><strong>{score(o)}</strong></div>)}</Panel></div></>}
 {tab==='company'&&<Panel title="Profilo azienda"><div className="formgrid">{Object.entries(data.company).map(([k,v])=><label key={k}>{k}<input disabled={!editing} value={v} type={k==='employees'?'number':'text'} onChange={e=>setData(d=>({...d,company:{...d.company,[k]:k==='employees'?+e.target.value:e.target.value}}))}/></label>)}</div></Panel>}
 {tab==='functions'&&<><Toolbar title="Mappa funzionale" text="Censisci tutte le funzioni e assegna un owner." add={addFunction}/><DataTable headers={['ID','Funzione','Responsabile','Persone','Missione','Sistemi']} rows={data.functions.map((f,i)=>[f.id,<Edit v={f.name} e={editing} s={v=>patch('functions',i,'name',v)}/>,<Edit v={f.owner} e={editing} s={v=>patch('functions',i,'owner',v)}/>,<Edit v={f.people} e={editing} s={v=>patch('functions',i,'people',+v)} type="number"/>,<Edit v={f.mission} e={editing} s={v=>patch('functions',i,'mission',v)}/>,<Edit v={f.systems} e={editing} s={v=>patch('functions',i,'systems',v)}/>])}/></>}
 {tab==='processes'&&<><Toolbar title="Process mapping" text="Misura lead time e touch time: la differenza evidenzia attese e colli di bottiglia." add={addProcess}/><DataTable headers={['ID','Processo','Funzione','Owner','Lead h','Touch h','Vol./mese','Pain point']} rows={data.processes.map((p,i)=>[p.id,<Edit v={p.name} e={editing} s={v=>patch('processes',i,'name',v)}/>,p.functionId,<Edit v={p.owner} e={editing} s={v=>patch('processes',i,'owner',v)}/>,<Edit v={p.lead} e={editing} s={v=>patch('processes',i,'lead',+v)} type="number"/>,<Edit v={p.touch} e={editing} s={v=>patch('processes',i,'touch',+v)} type="number"/>,p.volume,<Edit v={p.pain} e={editing} s={v=>patch('processes',i,'pain',v)}/>])}/></>}
 {tab==='tasks'&&<><Toolbar title="Task inventory" text="Una riga = una attività reale. Quantifica frequenza, tempo e persone." add={addTask}/><DataTable headers={['ID','Task','Processo','Freq/a','Min','Persone','€/h','Ore/a','Pain']} rows={data.tasks.map((t,i)=>[t.id,<Edit v={t.name} e={editing} s={v=>patch('tasks',i,'name',v)}/>,t.processId,<Edit v={t.frequency} e={editing} s={v=>patch('tasks',i,'frequency',+v)} type="number"/>,<Edit v={t.minutes} e={editing} s={v=>patch('tasks',i,'minutes',+v)} type="number"/>,t.people,t.cost,Math.round(t.frequency*t.minutes*t.people/60),<Edit v={t.pain} e={editing} s={v=>patch('tasks',i,'pain',v)}/>])}/></>}
 {tab==='surveys'&&<><div className="grid2"><Panel title="F01 · Organization Discovery"><p className="muted">Compilazione del responsabile di funzione. La risposta aggiorna direttamente la mappa funzionale.</p><div className="survey"><label>Funzione<input value={f01.name} onChange={e=>setF01({...f01,name:e.target.value})}/></label><label>Responsabile<input value={f01.owner} onChange={e=>setF01({...f01,owner:e.target.value})}/></label><label>N. persone<input type="number" value={f01.people} onChange={e=>setF01({...f01,people:+e.target.value})}/></label><label>Missione<textarea value={f01.mission} onChange={e=>setF01({...f01,mission:e.target.value})}/></label><label>Sistemi utilizzati<input value={f01.systems} onChange={e=>setF01({...f01,systems:e.target.value})}/></label><label>Principale inefficienza<textarea value={f01.pain} onChange={e=>setF01({...f01,pain:e.target.value})}/></label><button className="primary" onClick={submitF01}>Registra F01</button></div></Panel><Panel title="F03 · Task & Productivity"><p className="muted">Una compilazione = un task. La risposta alimenta automaticamente il Task Inventory.</p><div className="survey"><label>Task<input value={f03.name} onChange={e=>setF03({...f03,name:e.target.value})}/></label><label>Processo<select value={f03.processId} onChange={e=>setF03({...f03,processId:e.target.value})}><option value="">Seleziona...</option>{data.processes.map(p=><option key={p.id} value={p.id}>{p.id} · {p.name}</option>)}</select></label><label>Frequenza annua<input type="number" value={f03.frequency} onChange={e=>setF03({...f03,frequency:+e.target.value})}/></label><label>Minuti/esecuzione<input type="number" value={f03.minutes} onChange={e=>setF03({...f03,minutes:+e.target.value})}/></label><label>Persone<input type="number" value={f03.people} onChange={e=>setF03({...f03,people:+e.target.value})}/></label><label>Costo €/h<input type="number" value={f03.cost} onChange={e=>setF03({...f03,cost:+e.target.value})}/></label><label>Pain point<textarea value={f03.pain} onChange={e=>setF03({...f03,pain:e.target.value})}/></label><button className="primary" onClick={submitF03}>Registra F03</button></div></Panel></div><Panel title="Registro questionari"><DataTable headers={['ID','Modulo','Data','Sintesi']} rows={data.surveyLog.slice().reverse().map(x=>[x.id,x.form,new Date(x.submittedAt).toLocaleString('it-IT'),x.summary])}/></Panel></>}
 {tab==='opportunities'&&<Panel title="Opportunity Engine"><p className="muted">Score = tempo 25% + ripetitività 20% + automabilità 20% + dati 15% + frequenza 10% + impatto 10%, con penalità rischio.</p><DataTable headers={['ID','Opportunità','Sorgente','Score','Rischio']} rows={[...data.opportunities].sort((a,b)=>score(b)-score(a)).map(o=>[o.id,o.title,o.source,<b>{score(o)}/100</b>,o.risk])}/></Panel>}
 {tab==='usecases'&&<Panel title="Portfolio Use Case"><DataTable headers={['ID','Use case','Owner','KPI','Baseline','Target','Setup','OPEX','Benefit','ROI','Stato']} rows={data.useCases.map(u=>[u.id,u.title,u.owner||'—',u.kpi,u.baseline,u.target,money(u.setup),money(u.opex),money(u.benefit),`${u.setup+u.opex?Math.round((u.benefit-u.setup-u.opex)/(u.setup+u.opex)*100):0}%`,u.status])}/></Panel>}
 {tab==='data'&&<div className="grid2"><Panel title="Esporta tutti i dati"><p>Scarica un backup JSON completo del localStorage. Include dati azienda, funzioni, processi, task, opportunità, use case e registro questionari.</p><button className="primary" onClick={exportBackup}>Esporta backup JSON</button><small className="muted">Usalo anche come snapshot periodico o per trasferire il progetto su un altro browser.</small></Panel><Panel title="Importa backup JSON"><p>L’importazione sostituisce i dati presenti nel browser con quelli contenuti nel file selezionato.</p><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>e.target.files?.[0]&&importBackup(e.target.files[0])}/><button onClick={()=>fileRef.current?.click()}>Importa JSON</button><small className="muted">Prima di importare è consigliato esportare un backup dello stato attuale.</small></Panel></div>}
 {tab==='report'&&<Panel title="Company Intelligence Report"><div className="reportHero"><div><strong>{completion}%</strong><span>completezza dati</span></div><div><strong>{Math.round(metrics.hours)}</strong><span>ore baseline / anno</span></div><div><strong>{money(metrics.capacity)}</strong><span>capacity value</span></div><div><strong>{metrics.roi}%</strong><span>ROI portfolio indicativo</span></div></div><button className="primary" onClick={companyReport}>Genera PDF + Markdown + JSON</button><p className="muted">Il PDF è per persone e Direzione; Markdown/JSON sono pensati per una futura AI.</p></Panel>}
 </main></div>
}

function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Action({done,title,detail}:{done:boolean;title:string;detail:string}){return <div className="action"><span className={done?'dot done':'dot'}>{done?'✓':'!'}</span><div><b>{title}</b><small>{detail}</small></div></div>}
function Toolbar({title,text,add}:{title:string;text:string;add:()=>void}){return <div className="toolbar"><div><h3>{title}</h3><p>{text}</p></div><button onClick={add}>+ Aggiungi</button></div>}
function DataTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="tablewrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Edit({v,e,s,type='text'}:{v:string|number;e:boolean;s:(v:string)=>void;type?:string}){return e?<input className="inline" type={type} value={v} onChange={x=>s(x.target.value)}/>:<>{v||'—'}</>}
