import { useMemo, useRef, useState } from 'react'
import './data-vault.css'

const keys={workspace:'aito-store',maturity:'aito-f02-maturity',processDiscovery:'aito-f04-process-surveys',documents:'aito-doc-metadata',governance:'aito-governance'}
const safe=(k:string)=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
const download=(name:string,body:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

export default function DataVault(){
 const [tick,setTick]=useState(0),[notice,setNotice]=useState('')
 const ref=useRef<HTMLInputElement>(null)
 const stats=useMemo(()=>{void tick;const w=safe(keys.workspace)||{},m=w.f02Maturity||safe(keys.maturity)||[],d=w.documents||safe(keys.documents)||[],g=w.governance||safe(keys.governance)||[];return{functions:w.functions?.length||0,processes:w.processes?.length||0,tasks:w.tasks?.length||0,opportunities:w.opportunities?.length||0,useCases:w.useCases?.length||0,maturity:m.length,f04:(safe(keys.processDiscovery)||[]).length,documents:d.length,governance:g.length}},[tick])
 const payload=()=>{const w=safe(keys.workspace)||{};return{format:'AI_TRANSFORMATION_OS_FULL_BACKUP',version:'1.1',exported_at:new Date().toISOString(),storage:{[keys.workspace]:w,[keys.maturity]:w.f02Maturity||safe(keys.maturity)||[],[keys.processDiscovery]:safe(keys.processDiscovery)||[],[keys.documents]:w.documents||safe(keys.documents)||[],[keys.governance]:w.governance||safe(keys.governance)||[]},notes:{document_binary_files:'Not included. Document metadata is included; IndexedDB binary files remain browser-local.'}}}
 const exp=()=>{download(`ai-transformation-os-full-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload(),null,2));setNotice('Backup completo esportato.')}
 const imp=(file:File)=>{const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result));if(p.format!=='AI_TRANSFORMATION_OS_FULL_BACKUP'||!p.storage)throw new Error('format');Object.entries(keys).forEach(([,k])=>{if(Object.prototype.hasOwnProperty.call(p.storage,k))localStorage.setItem(k,JSON.stringify(p.storage[k]))});const w=safe(keys.workspace)||{};if(!w.f02Maturity&&p.storage[keys.maturity])w.f02Maturity=p.storage[keys.maturity];if(!w.documents&&p.storage[keys.documents])w.documents=p.storage[keys.documents];if(!w.governance&&p.storage[keys.governance])w.governance=p.storage[keys.governance];localStorage.setItem(keys.workspace,JSON.stringify(w));setTick(x=>x+1);setNotice('Backup completo importato. Il Central Workspace rileverà le modifiche e le salverà nel cloud.')}catch{setNotice('File non valido: usa un Full Backup generato da AI Transformation OS.')}};r.readAsText(file)}
 const exportAiPack=()=>{const p=payload();const w=p.storage[keys.workspace]||{};const ai={snapshot_date:p.exported_at,company:w.company||null,functions:w.functions||[],processes:w.processes||[],tasks:w.tasks||[],opportunities:w.opportunities||[],use_cases:w.useCases||[],survey_log:w.surveyLog||[],roadmap:w.milestones||[],maturity_assessments:w.f02Maturity||p.storage[keys.maturity],governance:w.governance||p.storage[keys.governance],process_discovery:p.storage[keys.processDiscovery],document_manifest:w.documents||p.storage[keys.documents],data_quality:{counts:stats,limitations:['Binary document files are not embedded in this JSON.']}};download('company-ai-ready-snapshot.json',JSON.stringify(ai,null,2));setNotice('AI-ready snapshot esportato.')}
 return <div className="vault"><header><div><a href="/">← AI Transformation OS</a><small>DATA PORTABILITY & AI READINESS</small><h1>Data Vault</h1><p>Un unico punto per salvare, trasferire e preparare tutti i dati raccolti per analisi future.</p></div></header>{notice&&<div className="vault-notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}<section className="vault-metrics">{Object.entries(stats).map(([k,v])=><article key={k}><span>{k}</span><b>{v}</b></article>)}</section><section className="vault-grid"><article><h2>Full Backup JSON</h2><p>Include workspace, AI Maturity F02, Governance, Process Discovery F04 e metadati Document Intelligence.</p><button onClick={exp}>Esporta backup completo</button></article><article><h2>Ripristino / trasferimento browser</h2><p>Importa il Full Backup su un altro PC o browser. I dati correnti con le stesse chiavi vengono sostituiti e poi sincronizzati dal Central Workspace.</p><button onClick={()=>ref.current?.click()}>Importa backup completo</button><input ref={ref} type="file" accept="application/json,.json" hidden onChange={e=>e.target.files?.[0]&&imp(e.target.files[0])}/></article><article><h2>AI-ready Company Snapshot</h2><p>Esporta un dataset lineare e strutturato che una futura AI potrà analizzare senza interpretare l’interfaccia.</p><button onClick={exportAiPack}>Esporta snapshot AI-ready</button></article><article className="warning"><h2>Documenti fisici</h2><p>I file caricati in Document Intelligence sono oggi salvati in IndexedDB del browser. Il backup include i metadati, non i file binari. Lo storage cloud dei file sarà una fase successiva.</p></article></section><section className="vault-flow"><h2>Portabilità del sistema</h2><p><b>Browser A</b> → Full Backup JSON → <b>Browser B</b> → Importa → workspace, assessment, governance, process discovery e document manifest ripristinati.</p></section></div>
}
