import { useEffect, useMemo, useState } from 'react'
import './documents.css'

type DocMeta={id:string;title:string;fileName:string;category:string;owner:string;functionCode:string;processCode:string;confidentiality:string;validation:string;version:string;documentDate:string;uploadedAt:string;size:number;mime:string;textPreview:string}

const META_KEY='aito-doc-metadata'
const DB='aito-documents-db', STORE='files'
const required=['Organigramma / Diagramma funzionale','Mappa processi','Manuale Qualità','Procedure operative','Job description','KPI / Report','Mappa sistemi e applicativi','Policy IT / AI / Privacy']
const categories=[...required,'Modulistica / Template','Documentazione progetti','R&D / Innovazione','Amministrazione / Controllo','HR / Organizzazione','Altro']
const readStore=()=>{try{return JSON.parse(localStorage.getItem('aito-store')||'{}')}catch{return {}}}

function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveBlob(id:string,file:File){const db=await openDb();await new Promise<void>((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});db.close()}
async function getBlob(id:string):Promise<Blob|undefined>{const db=await openDb();const out=await new Promise<Blob|undefined>((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();return out}
async function removeBlob(id:string){const db=await openDb();await new Promise<void>((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});db.close()}
const fmt=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`

export default function Documents(){
 const [docs,setDocs]=useState<DocMeta[]>(()=>{const central=readStore().documents;if(Array.isArray(central)&&central.length)return central;try{return JSON.parse(localStorage.getItem(META_KEY)||'[]')}catch{return[]}})
 const [notice,setNotice]=useState('')
 const [form,setForm]=useState({title:'',category:required[0],owner:'',functionCode:'',processCode:'',confidentiality:'Interno',validation:'Da validare',version:'1.0',documentDate:new Date().toISOString().slice(0,10)})
 useEffect(()=>{localStorage.setItem(META_KEY,JSON.stringify(docs));const s=readStore();localStorage.setItem('aito-store',JSON.stringify({...s,documents:docs}))},[docs])
 const covered=useMemo(()=>required.filter(x=>docs.some(d=>d.category===x)).length,[docs])
 const coverage=Math.round(covered/required.length*100)
 const upload=async(file:File)=>{const id=`DOC-${String(docs.length+1).padStart(4,'0')}`;let textPreview='';if(file.type.startsWith('text/')||/\.(txt|md|csv|json)$/i.test(file.name)){try{textPreview=(await file.text()).slice(0,12000)}catch{}}
  await saveBlob(id,file);const meta:DocMeta={id,title:form.title.trim()||file.name,fileName:file.name,category:form.category,owner:form.owner,functionCode:form.functionCode,processCode:form.processCode,confidentiality:form.confidentiality,validation:form.validation,version:form.version,documentDate:form.documentDate,uploadedAt:new Date().toISOString(),size:file.size,mime:file.type||'application/octet-stream',textPreview};setDocs(x=>[...x,meta]);setNotice(`${id} acquisito e indicizzato.`);setForm(x=>({...x,title:'',owner:'',functionCode:'',processCode:''}))}
 const download=async(d:DocMeta)=>{const b=await getBlob(d.id);if(!b){setNotice('File non disponibile in questo browser. I metadati restano presenti nel workspace centrale.');return}const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=d.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 const del=async(d:DocMeta)=>{await removeBlob(d.id);setDocs(x=>x.filter(v=>v.id!==d.id));setNotice(`${d.id} eliminato.`)}
 const exportManifest=()=>{const manifest={format:'AI_TRANSFORMATION_DOCUMENT_MANIFEST',version:'1.0',exported_at:new Date().toISOString(),coverage_percent:coverage,required_categories:required,documents:docs.map(({textPreview,...d})=>({...d,text_excerpt:textPreview||null,file_storage:'browser-indexeddb'}))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}));a.download='document-manifest.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 return <div className="docs-page"><header className="docs-head"><div><a href="/">← AI Transformation OS</a><small>DOCUMENT INTELLIGENCE</small><h1>Documenti & Knowledge</h1><p>Raccogli il patrimonio documentale, collegalo alla struttura aziendale e prepara un manifest leggibile da una futura AI.</p></div><div className="coverage"><strong>{coverage}%</strong><span>Document coverage</span><i><b style={{width:`${coverage}%`}}/></i></div></header>{notice&&<div className="doc-notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
 <section className="docs-grid"><div className="doc-panel"><h2>Checklist documentale</h2><p className="muted">Il sistema segnala cosa manca per una Discovery affidabile.</p><div className="checklist">{required.map(c=>{const hit=docs.filter(d=>d.category===c).length;return <div key={c} className={hit?'ok':''}><span>{hit?'✓':'!'}</span><div><b>{c}</b><small>{hit?`${hit} documento/i acquisiti`:'Mancante'}</small></div></div>})}</div></div>
 <div className="doc-panel"><h2>Acquisisci documento</h2><div className="upload-grid"><label>Titolo<input value={form.title} placeholder="Se vuoto uso il nome file" onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Owner<input value={form.owner} placeholder="Funzione o responsabile" onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>Funzione collegata<input value={form.functionCode} placeholder="es. FUNC-002" onChange={e=>setForm({...form,functionCode:e.target.value})}/></label><label>Processo collegato<input value={form.processCode} placeholder="es. PROC-0003" onChange={e=>setForm({...form,processCode:e.target.value})}/></label><label>Riservatezza<select value={form.confidentiality} onChange={e=>setForm({...form,confidentiality:e.target.value})}><option>Pubblico</option><option>Interno</option><option>Riservato</option><option>Strettamente riservato</option></select></label><label>Validazione<select value={form.validation} onChange={e=>setForm({...form,validation:e.target.value})}><option>Da validare</option><option>Validato</option><option>Obsoleto</option></select></label><label>Versione<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>Data documento<input type="date" value={form.documentDate} onChange={e=>setForm({...form,documentDate:e.target.value})}/></label></div><label className="drop">Seleziona file<input type="file" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><span>PDF, Word, Excel, PowerPoint, immagini, testo o altri documenti aziendali</span></label><small className="muted">Il file resta nel browser tramite IndexedDB; i metadati sono sincronizzati nel Central Workspace. Su un altro browser il documento sarà visibile nel registro, ma il file binario dovrà essere nuovamente disponibile o migrato a storage cloud in una release successiva.</small></div></section>
 <section className="doc-panel"><div className="doc-toolbar"><div><h2>Document Register</h2><p className="muted">{docs.length} documenti registrati · {docs.filter(d=>d.validation==='Validato').length} validati</p></div><button onClick={exportManifest}>Esporta manifest AI-ready</button></div><div className="doc-table"><table><thead><tr><th>ID</th><th>Documento</th><th>Categoria</th><th>Owner / link</th><th>Versione</th><th>Stato</th><th>File</th><th></th></tr></thead><tbody>{docs.length===0?<tr><td colSpan={8} className="empty">Nessun documento acquisito.</td></tr>:docs.map(d=><tr key={d.id}><td><b>{d.id}</b></td><td><b>{d.title}</b><small>{d.fileName} · {fmt(d.size)}</small></td><td>{d.category}<small>{d.confidentiality}</small></td><td>{d.owner||'—'}<small>{[d.functionCode,d.processCode].filter(Boolean).join(' · ')||'Nessun collegamento'}</small></td><td>{d.version}<small>{d.documentDate}</small></td><td><span className={`badge ${d.validation==='Validato'?'valid':''}`}>{d.validation}</span></td><td><button className="linkbtn" onClick={()=>download(d)}>Scarica</button></td><td><button className="danger" onClick={()=>del(d)}>×</button></td></tr>)}</tbody></table></div></section>
 <section className="doc-panel ai-ready"><h2>Come userà questi dati una futura AI</h2><div><p><b>1. Organizzazione</b><br/>Organigrammi, job description e mappe funzionali aiutano a ricostruire struttura, responsabilità e interfacce.</p><p><b>2. Processi</b><br/>Procedure, manuali e modelli aiutano a confrontare processo dichiarato e processo rilevato dai questionari.</p><p><b>3. Ottimizzazione</b><br/>KPI, report, sistemi e pain point possono essere correlati a task e opportunità per generare raccomandazioni tracciabili.</p></div></section></div>}
