import {useMemo,useState} from 'react'
import './surveys.css'
import {scoreF01,type F01V2,type Scale5} from './surveyV2'

const split=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean)
export default function F01V2Pilot(){
 const [saved,setSaved]=useState(false)
 const [f,setF]=useState({functionName:'',owner:'',people:0,mission:'',responsibilities:'',outputs:'',customers:'',kpis:'',performancePain:'',dependencies:'',incomingInputs:'',outgoingOutputs:'',handoffPain:'',externalDependencies:'',systems:'',manualAssets:'',criticalData:'',knowledgeConcentration:3 as Scale5,procedureMaturity:3 as Scale5,topPain:'',manualAreas:'',expectedChanges:'',priorities:'',answerConfidence:3 as Scale5})
 const model:F01V2=useMemo(()=>({schemaVersion:'F01@2.0',functionName:f.functionName,owner:f.owner,people:+f.people||0,mission:f.mission,responsibilities:split(f.responsibilities),outputs:split(f.outputs),customers:split(f.customers),kpis:split(f.kpis),performancePain:f.performancePain,dependencies:split(f.dependencies),incomingInputs:split(f.incomingInputs),outgoingOutputs:split(f.outgoingOutputs),handoffPain:f.handoffPain,externalDependencies:split(f.externalDependencies),systems:split(f.systems),manualAssets:split(f.manualAssets),criticalData:split(f.criticalData),knowledgeConcentration:f.knowledgeConcentration,procedureMaturity:f.procedureMaturity,topPain:split(f.topPain),manualAreas:split(f.manualAreas),expectedChanges:split(f.expectedChanges),priorities:split(f.priorities),answerConfidence:f.answerConfidence}),[f])
 const score=useMemo(()=>scoreF01(model),[model])
 const set=(k:string,v:any)=>{setSaved(false);setF(x=>({...x,[k]:v}))}
 const Lines=({k,label,help}:{k:keyof typeof f,label:string,help?:string})=><label className="wide">{label}{help&&<small>{help}</small>}<textarea value={String(f[k]??'')} onChange={e=>set(k,e.target.value)} placeholder="Una voce per riga"/></label>
 return <div className="survey-page"><header className="survey-head"><div><a href="/surveys">← Questionari & Assessment</a><small>V2 PILOT · NON ATTIVO PER I DIPENDENTI</small><h1>F01 v2 · Organization & Function Discovery</h1><p>Prototipo del nuovo questionario per i responsabili di funzione. I dati inseriti qui non vengono salvati nel workspace reale.</p></div><a href="/v1-readiness">V1 Readiness</a></header>
 <section className="metric-grid"><article><span>Baseline score</span><b>{score.score}/100</b></article><article><span>Confidence</span><b>{score.confidence}/100</b></article><article><span>Stato</span><b>{score.band}</b></article><article><span>Gap</span><b>{score.gaps.length}</b></article></section>
 <section className="panel form-panel"><div className="intro"><h2>A. Identità e perimetro</h2><p>Definisce la funzione, la responsabilità e la dimensione della baseline organizzativa.</p></div><div className="form-grid"><label>Funzione / area<input value={f.functionName} onChange={e=>set('functionName',e.target.value)}/></label><label>Responsabile / owner<input value={f.owner} onChange={e=>set('owner',e.target.value)}/></label><label>Numero persone<input type="number" min="0" value={f.people} onChange={e=>set('people',+e.target.value)}/></label><label>Confidence del rispondente<select value={f.answerConfidence} onChange={e=>set('answerConfidence',+e.target.value as Scale5)}><option value="1">1 · molto bassa</option><option value="2">2 · bassa</option><option value="3">3 · media</option><option value="4">4 · alta</option><option value="5">5 · molto alta</option></select></label><label className="wide">Missione della funzione<textarea value={f.mission} onChange={e=>set('mission',e.target.value)}/></label><Lines k="responsibilities" label="Principali responsabilità"/><Lines k="outputs" label="Output / deliverable principali"/></div></section>
 <section className="panel form-panel"><div className="intro"><h2>B. Valore, clienti e KPI</h2></div><div className="form-grid"><Lines k="customers" label="Clienti interni / esterni"/><Lines k="kpis" label="KPI attualmente utilizzati"/><label className="wide">Quali output o KPI sono più difficili da rispettare e perché?<textarea value={f.performancePain} onChange={e=>set('performancePain',e.target.value)}/></label></div></section>
 <section className="panel form-panel"><div className="intro"><h2>C. Interfacce e dipendenze</h2></div><div className="form-grid"><Lines k="dependencies" label="Funzioni con cui interagisci maggiormente"/><Lines k="incomingInputs" label="Input ricevuti da altre funzioni"/><Lines k="outgoingOutputs" label="Informazioni/documenti inviati ad altre funzioni"/><label className="wide">Dove gli handoff creano attese o rilavorazioni?<textarea value={f.handoffPain} onChange={e=>set('handoffPain',e.target.value)}/></label><Lines k="externalDependencies" label="Fornitori / partner esterni critici"/></div></section>
 <section className="panel form-panel"><div className="intro"><h2>D. Sistemi, dati e conoscenza</h2></div><div className="form-grid"><Lines k="systems" label="Applicazioni e sistemi principali"/><Lines k="manualAssets" label="Excel/file/manualità critiche"/><Lines k="criticalData" label="Dati o documenti critici gestiti"/><label>Conoscenza concentrata su poche persone<select value={f.knowledgeConcentration} onChange={e=>set('knowledgeConcentration',+e.target.value as Scale5)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Procedure documentate e aggiornate<select value={f.procedureMaturity} onChange={e=>set('procedureMaturity',+e.target.value as Scale5)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label></div></section>
 <section className="panel form-panel"><div className="intro"><h2>E. Problemi e priorità</h2></div><div className="form-grid"><Lines k="topPain" label="Tre principali problemi operativi"/><Lines k="manualAreas" label="Aree più manuali o ripetitive"/><Lines k="expectedChanges" label="Cambiamenti previsti nei prossimi 12–24 mesi"/><Lines k="priorities" label="Priorità di miglioramento"/></div></section>
 <section className="panel"><h2>Diagnostica pilota</h2><p><b>{score.band}</b> · Score {score.score}/100 · Confidence {score.confidence}/100</p><p><b>Gap:</b> {score.gaps.length?score.gaps.join(', '):'nessun gap principale'}</p><p><b>Segnali:</b> {score.drivers.join(' · ')}</p><button className="primary" onClick={()=>setSaved(true)}>Simula completamento F01 v2</button>{saved&&<p className="survey-notice">Simulazione completata. Nessun dato reale è stato modificato.</p>}</section>
 </div>
}
