import {useMemo,useState} from 'react'
import './surveys.css'
import {scoreF01,type F01V2,type Scale5} from './surveyV2'
const split=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean)
const Guide=({text}:{text:string})=><small style={{display:'block',margin:'4px 0 7px',color:'#667085',lineHeight:1.4}}><b>Esempio:</b> {text}</small>
export default function F01V2Pilot(){
 const [saved,setSaved]=useState(false)
 const [f,setF]=useState({functionName:'',owner:'',people:0,mission:'',responsibilities:'',outputs:'',customers:'',kpis:'',performancePain:'',dependencies:'',incomingInputs:'',outgoingOutputs:'',handoffPain:'',externalDependencies:'',systems:'',manualAssets:'',criticalData:'',knowledgeConcentration:3 as Scale5,procedureMaturity:3 as Scale5,topPain:'',manualAreas:'',expectedChanges:'',priorities:'',answerConfidence:3 as Scale5})
 const model:F01V2=useMemo(()=>({schemaVersion:'F01@2.0',functionName:f.functionName,owner:f.owner,people:+f.people||0,mission:f.mission,responsibilities:split(f.responsibilities),outputs:split(f.outputs),customers:split(f.customers),kpis:split(f.kpis),performancePain:f.performancePain,dependencies:split(f.dependencies),incomingInputs:split(f.incomingInputs),outgoingOutputs:split(f.outgoingOutputs),handoffPain:f.handoffPain,externalDependencies:split(f.externalDependencies),systems:split(f.systems),manualAssets:split(f.manualAssets),criticalData:split(f.criticalData),knowledgeConcentration:f.knowledgeConcentration,procedureMaturity:f.procedureMaturity,topPain:split(f.topPain),manualAreas:split(f.manualAreas),expectedChanges:split(f.expectedChanges),priorities:split(f.priorities),answerConfidence:f.answerConfidence}),[f])
 const score=useMemo(()=>scoreF01(model),[model]);const set=(k:string,v:any)=>{setSaved(false);setF(x=>({...x,[k]:v}))}
 const Lines=({k,label,example,help}:{k:keyof typeof f,label:string,example:string,help?:string})=><label className="wide">{label}{help&&<small>{help}</small>}<Guide text={example}/><textarea value={String(f[k]??'')} onChange={e=>set(k,e.target.value)} placeholder="Una voce per riga"/></label>
 return <div className="survey-page"><header className="survey-head"><div><a href="/surveys">← Questionari & Assessment</a><small>V2 PILOT · NON ATTIVO PER I DIPENDENTI</small><h1>F01 v2 · Organization & Function Discovery</h1><p>Prototipo del nuovo questionario per i responsabili di funzione. Ogni domanda contiene un esempio orientativo: serve a chiarire il livello di dettaglio atteso, non deve essere copiato. I dati inseriti qui non vengono salvati nel workspace reale.</p></div><a href="/v1-readiness">V1 Readiness</a></header>
 <section className="metric-grid"><article><span>Baseline score</span><b>{score.score}/100</b></article><article><span>Confidence</span><b>{score.confidence}/100</b></article><article><span>Stato</span><b>{score.band}</b></article><article><span>Gap</span><b>{score.gaps.length}</b></article></section>
 <section className="panel form-panel"><div className="intro"><h2>A. Identità e perimetro</h2><p>Definisce la funzione, la responsabilità e la dimensione della baseline organizzativa.</p></div><div className="form-grid"><label>Funzione / area<Guide text="Acquisti; R&D; Amministrazione e Finanza"/><input value={f.functionName} onChange={e=>set('functionName',e.target.value)}/></label><label>Responsabile / owner<Guide text="Mario Rossi — Responsabile Acquisti"/><input value={f.owner} onChange={e=>set('owner',e.target.value)}/></label><label>Numero persone<Guide text="6 persone stabilmente assegnate alla funzione"/><input type="number" min="0" value={f.people} onChange={e=>set('people',+e.target.value)}/></label><label>Confidence del rispondente<Guide text="4 · alta, se conosci bene attività, KPI e sistemi della funzione"/><select value={f.answerConfidence} onChange={e=>set('answerConfidence',+e.target.value as Scale5)}><option value="1">1 · molto bassa</option><option value="2">2 · bassa</option><option value="3">3 · media</option><option value="4">4 · alta</option><option value="5">5 · molto alta</option></select></label><label className="wide">Missione della funzione<Guide text="Garantire approvvigionamenti di materiali e servizi nei tempi richiesti, alle condizioni economiche concordate e nel rispetto dei requisiti tecnici."/><textarea value={f.mission} onChange={e=>set('mission',e.target.value)}/></label><Lines k="responsibilities" label="Principali responsabilità" example={'Gestione richieste di acquisto; selezione fornitori; emissione ordini; monitoraggio consegne'}/><Lines k="outputs" label="Output / deliverable principali" example={'Ordini di acquisto; contratti; vendor list aggiornata; report consegne'}/></div></section>
 <section className="panel form-panel"><div className="intro"><h2>B. Valore, clienti e KPI</h2></div><div className="form-grid"><Lines k="customers" label="Clienti interni / esterni" example={'Project Manager; Produzione; Amministrazione; cliente finale'}/><Lines k="kpis" label="KPI attualmente utilizzati" example={'Tempo medio emissione ordine; % consegne puntuali; saving rispetto al budget'}/><label className="wide">Quali output o KPI sono più difficili da rispettare e perché?<Guide text="Le consegne puntuali sono difficili da rispettare perché le richieste arrivano spesso incomplete e richiedono chiarimenti tecnici."/><textarea value={f.performancePain} onChange={e=>set('performancePain',e.target.value)}/></label></div></section>
 <section className="panel form-panel"><div className="intro"><h2>C. Interfacce e dipendenze</h2></div><div className="form-grid"><Lines k="dependencies" label="Funzioni con cui interagisci maggiormente" example={'Engineering; Project Management; Magazzino; Amministrazione'}/><Lines k="incomingInputs" label="Input ricevuti da altre funzioni" example={'Richieste di acquisto; specifiche tecniche; distinta materiali; budget di commessa'}/><Lines k="outgoingOutputs" label="Informazioni/documenti inviati ad altre funzioni" example={'Ordine confermato; data prevista consegna; costo aggiornato; documentazione fornitore'}/><label className="wide">Dove gli handoff creano attese o rilavorazioni?<Guide text="La richiesta passa da Engineering ad Acquisti senza codice materiale completo; Acquisti deve chiedere integrazioni e il processo si ferma."/><textarea value={f.handoffPain} onChange={e=>set('handoffPain',e.target.value)}/></label><Lines k="externalDependencies" label="Fornitori / partner esterni critici" example={'Fornitore quadri elettrici; spedizioniere internazionale; laboratorio di certificazione'}/></div></section>
 <section className="panel form-panel"><div className="intro"><h2>D. Sistemi, dati e conoscenza</h2></div><div className="form-grid"><Lines k="systems" label="Applicazioni e sistemi principali" example={'ERP aziendale; Outlook; Excel; Teams; portale fornitori'}/><Lines k="manualAssets" label="Excel/file/manualità critiche" example={'Excel monitoraggio consegne; tabella prezzi fornitori mantenuta manualmente; email per approvazioni'}/><Lines k="criticalData" label="Dati o documenti critici gestiti" example={'Prezzi e condizioni fornitori; ordini; specifiche tecniche; certificati; date consegna'}/><label>Conoscenza concentrata su poche persone<Guide text="5/5 se una sola persona conosce fornitori, procedure o file indispensabili e la sua assenza bloccherebbe il lavoro"/><select value={f.knowledgeConcentration} onChange={e=>set('knowledgeConcentration',+e.target.value as Scale5)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Procedure documentate e aggiornate<Guide text="5/5 se le procedure sono formalizzate, aggiornate e realmente utilizzate; 1/5 se il lavoro dipende quasi interamente dalla prassi personale"/><select value={f.procedureMaturity} onChange={e=>set('procedureMaturity',+e.target.value as Scale5)}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label></div></section>
 <section className="panel form-panel"><div className="intro"><h2>E. Problemi e priorità</h2></div><div className="form-grid"><Lines k="topPain" label="Tre principali problemi operativi" example={'Richieste incomplete; difficoltà nel conoscere lo stato reale delle consegne; troppe approvazioni via email'}/><Lines k="manualAreas" label="Aree più manuali o ripetitive" example={'Copia dati da offerte a ERP; aggiornamento Excel consegne; preparazione report settimanale'}/><Lines k="expectedChanges" label="Cambiamenti previsti nei prossimi 12–24 mesi" example={'Nuovo ERP; crescita volumi del 20%; apertura nuova sede; introduzione nuovo processo di qualifica fornitori'}/><Lines k="priorities" label="Priorità di miglioramento" example={'Ridurre tempi di emissione ordine; automatizzare monitoraggio consegne; avere dati fornitori in un unico punto'}/></div></section>
 <section className="panel"><h2>Diagnostica pilota</h2><p><b>{score.band}</b> · Score {score.score}/100 · Confidence {score.confidence}/100</p><p><b>Gap:</b> {score.gaps.length?score.gaps.join(', '):'nessun gap principale'}</p><p><b>Segnali:</b> {score.drivers.join(' · ')}</p><button className="primary" onClick={()=>setSaved(true)}>Simula completamento F01 v2</button>{saved&&<p className="survey-notice">Simulazione completata. Nessun dato reale è stato modificato.</p>}</section>
 </div>
}
