import {useEffect,useMemo,useState} from 'react'
import './guided-journey.css'
const read=(k:string,f:any)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
type Invite={form_code:string;submitted_at:string|null}
export default function GuidedJourney(){const [data]=useState<any>(()=>read('aito-store',{})),[inv,setInv]=useState<Invite[]>([]);useEffect(()=>{fetch('/api/survey-link').then(r=>r.json()).then(j=>setInv(j.items||[])).catch(()=>{})},[]);const j=useMemo(()=>{const funcs=data.functions||[],ins=data.employeeInsights||[],tasks=data.tasks||[],opps=data.opportunities||[],cases=data.businessCases||[],benefits=data.benefits||[],f03=inv.filter(i=>i.form_code==='F03'),done=f03.filter(i=>i.submitted_at);const steps=[
{phase:'1 · PREPARA',title:'Definisci azienda e funzioni',why:'Serve a sapere quali aree e persone devono essere coinvolte.',done:funcs.length>0,metric:`${funcs.length} funzioni definite`,href:'/',action:'Apri Company Model'},
{phase:'2 · RACCOGLI',title:'Prepara la campagna F03',why:'Carica dipendenti, funzione e ruolo e genera gli inviti personali.',done:f03.length>0,metric:`${f03.length} inviti creati`,href:'/survey-campaign',action:'Gestisci campagna'},
{phase:'3 · ASCOLTA',title:'Raccogli le interviste',why:'I dipendenti descrivono lavoro reale, tempi, strumenti, problemi e idee.',done:done.length>0,metric:`${done.length}/${f03.length||0} completati`,href:'/survey-inbox',action:'Apri Survey Inbox'},
{phase:'4 · VALIDA',title:'Controlla qualità e confidence',why:'Non passare all’analisi finché le evidenze non sono sufficienti e rappresentative.',done:ins.some((i:any)=>(+i.qualityScore||0)>=75),metric:`${ins.length} interviste importate`,href:'/survey-coverage',action:'Verifica Confidence'},
{phase:'5 · COMPRENDI',title:'Analizza inefficienze e voce dei dipendenti',why:'Cerca pattern ricorrenti prima di pensare alla soluzione tecnologica.',done:ins.length>=2&&tasks.length>0,metric:`${tasks.length} attività · ${ins.length} insight`,href:'/employee-insights',action:'Analizza insight'},
{phase:'6 · PRIORITIZZA',title:'Trasforma evidenze in opportunità',why:'Valuta impatto, fattibilità e priorità degli interventi.',done:opps.length>0,metric:`${opps.length} opportunità`,href:'/opportunity-engine',action:'Opportunity Engine'},
{phase:'7 · DIMOSTRA',title:'Costruisci il business case',why:'Quantifica costi, saving, ROI e payback prima di investire.',done:cases.length>0,metric:`${cases.length} business case`,href:'/business-case',action:'Business Case Lab'},
{phase:'8 · DECIDI',title:'Applica readiness e governance',why:'Verifica dati, owner, rischio, compliance e condizioni per partire.',done:false,metric:'Gate metodologico',href:'/readiness',action:'Readiness Gate'},
{phase:'9 · REALIZZA',title:'Esegui PoC e iniziative',why:'Implementa in modo controllato, con baseline e obiettivi misurabili.',done:false,metric:'Portfolio iniziative',href:'/control-center',action:'Control Center'},
{phase:'10 · MISURA',title:'Misura benefici e riferisci alla Direzione',why:'Confronta before/after e comunica valore realizzato e prossime azioni.',done:benefits.length>0,metric:`${benefits.length} benefici registrati`,href:'/benefits',action:'Benefits Tracker'}];const current=steps.findIndex(s=>!s.done),completed=steps.filter(s=>s.done).length;return{steps,current:current<0?steps.length-1:current,completed}},[data,inv]);return <main className="journey"><header><div><a href="/">← Home</a><small>AI TRANSFORMATION · GUIDED JOURNEY</small><h1>Percorso guidato</h1><p>Questa è la sequenza operativa consigliata. In ogni momento puoi vedere cosa è stato fatto, perché serve e quale attività eseguire dopo.</p></div><a className="next" href={j.steps[j.current].href}>Continua da qui →</a></header><section className="journey-summary"><div><b>{j.completed}/{j.steps.length}</b><span>fasi completate</span></div><div className="overall"><i style={{width:`${j.completed/j.steps.length*100}%`}}/></div><div><b>{Math.round(j.completed/j.steps.length*100)}%</b><span>percorso</span></div></section><section className="roadmap">{j.steps.map((s,i)=><article key={s.title} className={`${s.done?'done':''} ${i===j.current?'current':''}`}><div className="marker">{s.done?'✓':i+1}</div><div className="body"><small>{s.phase}</small><h2>{s.title}</h2><p>{s.why}</p><span>{s.metric}</span></div><div className="state"><b>{s.done?'FATTO':i===j.current?'DA FARE ORA':'SUCCESSIVO'}</b><a href={s.href}>{s.action} →</a></div></article>)}</section><section className="journey-help"><h2>Come usare il percorso</h2><p>Segui le fasi nell'ordine. Il sistema marca automaticamente alcune attività quando trova dati reali; i gate metodologici restano intenzionalmente da verificare prima di avanzare. Se una fase precedente cambia, torna a validarla prima di usare risultati successivi.</p></section></main>}
