import {useMemo,useState} from 'react'
import './opportunity-engine.css'

type Task={id:string;name:string;processId:string;frequency:number;minutes:number;people:number;cost:number;repeat:number;data:number;judgement:number;pain:string}
type Store={tasks?:Task[];processes?:any[];opportunities?:any[];useCases?:any[]}
const read=()=>{try{return JSON.parse(localStorage.getItem('aito-store')||'{}') as Store}catch{return {}}}
const save=(x:Store)=>localStorage.setItem('aito-store',JSON.stringify(x))
const clamp=(n:number)=>Math.max(1,Math.min(5,Math.round(n)))
const eur=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
const classify=(t:Task)=>{const txt=(t.name+' '+t.pain).toLowerCase();if(/report|verbale|riass|document|capitol|specific|email|testo/.test(txt))return 'AI COPILOT';if(/ricerca|scouting|bando|monitor|verifica/.test(txt))return 'AI INTELLIGENCE';if(/inser|copia|trasfer|aggiorn|caric|registr/.test(txt))return 'AUTOMAZIONE';return t.judgement>=4?'AI ASSISTANT':'AUTOMAZIONE'}
export default function OpportunityEngine(){
 const [data,setData]=useState<Store>(()=>read()),[saving,setSaving]=useState('')
 const rows=useMemo(()=>(data.tasks||[]).map(t=>{const hours=(+t.frequency||0)*(+t.minutes||0)*(+t.people||1)/60;const value=hours*(+t.cost||35);const repeat=clamp(+t.repeat||3),dat=clamp(+t.data||3),jud=clamp(+t.judgement||3);const automation=clamp(6-jud+(repeat>=4?1:0));const freq=clamp(hours>=400?5:hours>=200?4:hours>=80?3:hours>=30?2:1);const impact=clamp(value>=30000?5:value>=15000?4:value>=6000?3:value>=2000?2:1);const risk=clamp(jud>=5?4:jud>=4?3:2);const score=Math.max(0,Math.min(100,Math.round(((5*.25+repeat*.20+automation*.20+dat*.15+freq*.10+impact*.10)/5)*100-(risk-1)*5)));const saveRate=Math.max(.15,Math.min(.7,.15+(automation-1)*.10+(repeat-1)*.04-(risk-1)*.03));const hoursSaved=Math.round(hours*saveRate);const annualBenefit=Math.round(value*saveRate);const type=classify(t);const priority=score>=80?'P1':score>=65?'P2':score>=50?'P3':'P4';return{t,hours,value,repeat,dat,automation,freq,impact,risk,score,hoursSaved,annualBenefit,type,priority}}).sort((a,b)=>b.score-a.score),[data])
 const generate=()=>{const existing=data.opportunities||[];const bySource=new Map(existing.map((x:any)=>[x.source,x]));const opps=rows.map((r,i)=>({...bySource.get(r.t.id),id:(bySource.get(r.t.id) as any)?.id||`OPP-${String(i+1).padStart(4,'0')}`,title:r.t.name,source:r.t.id,time:5,repeat:r.repeat,automation:r.automation,data:r.dat,frequency:r.freq,impact:r.impact,risk:r.risk,engine:{type:r.type,priority:r.priority,score:r.score,hoursBaseline:Math.round(r.hours),hoursSaved:r.hoursSaved,annualBenefit:r.annualBenefit,generatedAt:new Date().toISOString()}}));const next={...data,opportunities:opps};setData(next);save(next);setSaving(`${opps.length} opportunità generate e salvate nel workspace.`)}
 const promote=(r:any)=>{const u=data.useCases||[];if(u.some((x:any)=>x.sourceOpportunity===r.t.id)){setSaving('Use case già presente.');return}const setup=Math.max(2500,Math.round(r.annualBenefit*.25/500)*500),opex=Math.max(1000,Math.round(r.annualBenefit*.08/500)*500);const uc={id:`UC-${String(u.length+1).padStart(3,'0')}`,title:r.t.name,owner:'',kpi:'Ore annue impiegate sul task',baseline:Math.round(r.hours),target:Math.max(0,Math.round(r.hours-r.hoursSaved)),setup,opex,benefit:r.annualBenefit,status:'IDEA',sourceOpportunity:r.t.id};const next={...data,useCases:[...u,uc]};setData(next);save(next);setSaving('Use case creato. Completa owner, KPI e costi prima del PoC.')}
 const totals=rows.reduce((a,r)=>({h:a.h+r.hours,s:a.s+r.hoursSaved,b:a.b+r.annualBenefit}),{h:0,s:0,b:0})
 return <main className="oe"><header><a href="/">← Workspace</a><small>OPPORTUNITY ENGINE</small><h1>Prioritizzazione automatica</h1><p>Trasforma il Task Inventory in una pipeline misurabile di opportunità AI e automazione. Le stime sono indicative: vanno validate con process owner e dati reali prima del business case.</p></header>{saving&&<div className="oe-note">{saving}</div>}<section className="oe-cards"><div><span>Task analizzati</span><b>{rows.length}</b></div><div><span>Baseline</span><b>{Math.round(totals.h)} h/a</b></div><div><span>Potenziale recupero</span><b>{Math.round(totals.s)} h/a</b></div><div><span>Capacity value</span><b>{eur(totals.b)}/a</b></div></section><section className="oe-guide"><div><b>1. Raccogli</b><span>F03 alimenta task, frequenza, tempo, persone e pain point.</span></div><div><b>2. Calcola</b><span>Score 0–100 combina ripetitività, automabilità, dati, frequenza, impatto e rischio.</span></div><div><b>3. Valida</b><span>Conferma baseline e saving con il responsabile del processo.</span></div><div><b>4. Seleziona</b><span>Promuovi P1/P2 a business case e PoC.</span></div></section><div className="oe-actions"><button onClick={generate}>Genera / aggiorna Opportunity Map</button><span>P1 ≥80 · P2 65–79 · P3 50–64 · P4 &lt;50</span></div><section className="oe-table"><table><thead><tr><th>Priorità</th><th>Task</th><th>Tipo</th><th>Score</th><th>Baseline</th><th>Saving stimato</th><th>Valore annuo</th><th>Rischio</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.t.id}><td><strong className={`p ${r.priority}`}>{r.priority}</strong></td><td><b>{r.t.name}</b><small>{r.t.pain||'Pain point non indicato'}</small></td><td>{r.type}</td><td><strong>{r.score}/100</strong></td><td>{Math.round(r.hours)} h/a</td><td>{r.hoursSaved} h/a</td><td>{eur(r.annualBenefit)}</td><td>{r.risk}/5</td><td><button onClick={()=>promote(r)}>Crea use case</button></td></tr>)}</tbody></table>{!rows.length&&<p>Nessun task disponibile. Completa prima F03 / Task Inventory.</p>}</section><section className="oe-method"><h2>Metodo di scoring</h2><p><b>Opportunity Score</b> = tempo 25% + ripetitività 20% + automabilità 20% + disponibilità dati 15% + frequenza 10% + impatto 10%, con penalizzazione per rischio. Il motore non sostituisce la validazione: rende confrontabili le opportunità e documenta l’ipotesi iniziale.</p></section></main>
}