import {useMemo,useState} from 'react'
import './public-survey.css'

const getParts=()=>{const p=location.pathname.split('/').filter(Boolean);return{form:(p[1]||'F02').toUpperCase(),token:p[2]||''}}
export default function PublicSurvey(){
 const {form,token}=getParts(); const [sent,setSent]=useState(false); const [msg,setMsg]=useState('');
 const [name,setName]=useState(''),[email,setEmail]=useState('');
 const [data,setData]=useState<any>({functionName:'',role:'',skills:3,adoption:3,process:3,data:3,technology:3,governance:3,processName:'',owner:'',trigger:'',input:'',output:'',steps:'',systems:'',volume:0,lead:0,touch:0,waiting:'',rework:'',kpi:'',pain:'',function:'',people:0,mission:'',task:'',frequency:0,minutes:0,participants:1,cost:35,repeat:3,judgement:3})
 const title=useMemo(()=>({F01:'Organization Discovery',F02:'AI Maturity Assessment',F03:'Task & Productivity',F04:'Process Discovery'} as any)[form]||form,[form])
 const submit=async()=>{setMsg('Invio in corso...');try{const r=await fetch('/api/survey-submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,formCode:form,respondentName:name,respondentEmail:email,payload:data})});const j=await r.json();if(!r.ok)throw new Error(j.error||'errore');setSent(true);setMsg('Risposta registrata correttamente. Grazie per la collaborazione.')}catch(e:any){setMsg(e.message==='backend_not_configured'?'Il backend centrale non è ancora configurato. Segnala questo messaggio al responsabile del programma.':'Invio non riuscito: '+e.message)}}
 if(sent)return <main className="pub"><section className="pub-card success"><small>AI TRANSFORMATION</small><h1>Compilazione completata</h1><p>{msg}</p></section></main>
 return <main className="pub"><section className="pub-card"><small>AI TRANSFORMATION · {form}</small><h1>{title}</h1><p className="intro">Le informazioni servono a comprendere e migliorare processi e strumenti. Non sono utilizzate per valutare la produttività individuale.</p><div className="grid"><label>Nome (opzionale)<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email (opzionale)<input value={email} onChange={e=>setEmail(e.target.value)}/></label></div>
 {form==='F01'&&<div className="grid"><label>Funzione / area<input value={data.function} onChange={e=>setData({...data,function:e.target.value})}/></label><label>Numero persone<input type="number" value={data.people} onChange={e=>setData({...data,people:+e.target.value})}/></label><label className="wide">Missione<textarea value={data.mission} onChange={e=>setData({...data,mission:e.target.value})}/></label><label className="wide">Sistemi utilizzati<textarea value={data.systems} onChange={e=>setData({...data,systems:e.target.value})}/></label><label className="wide">Principali criticità<textarea value={data.pain} onChange={e=>setData({...data,pain:e.target.value})}/></label></div>}
 {form==='F02'&&<><div className="grid"><label>Funzione / area<input value={data.functionName} onChange={e=>setData({...data,functionName:e.target.value})}/></label><label>Ruolo<input value={data.role} onChange={e=>setData({...data,role:e.target.value})}/></label></div><div className="sliders">{[['skills','Skills'],['adoption','Adoption'],['process','Process'],['data','Data'],['technology','Technology'],['governance','Governance']].map(([k,l])=><label key={k}><span>{l}</span><input type="range" min="1" max="5" value={data[k]} onChange={e=>setData({...data,[k]:+e.target.value})}/><b>{data[k]}/5</b></label>)}</div></>}
 {form==='F03'&&<div className="grid"><label>Attività / task<input value={data.task} onChange={e=>setData({...data,task:e.target.value})}/></label><label>Frequenza annua<input type="number" value={data.frequency} onChange={e=>setData({...data,frequency:+e.target.value})}/></label><label>Minuti per esecuzione<input type="number" value={data.minutes} onChange={e=>setData({...data,minutes:+e.target.value})}/></label><label>Persone coinvolte<input type="number" value={data.participants} onChange={e=>setData({...data,participants:+e.target.value})}/></label><label className="wide">Pain point<textarea value={data.pain} onChange={e=>setData({...data,pain:e.target.value})}/></label></div>}
 {form==='F04'&&<div className="grid"><label>Nome processo<input value={data.processName} onChange={e=>setData({...data,processName:e.target.value})}/></label><label>Process owner<input value={data.owner} onChange={e=>setData({...data,owner:e.target.value})}/></label><label>Trigger<input value={data.trigger} onChange={e=>setData({...data,trigger:e.target.value})}/></label><label>Sistemi<input value={data.systems} onChange={e=>setData({...data,systems:e.target.value})}/></label><label>Volume/mese<input type="number" value={data.volume} onChange={e=>setData({...data,volume:+e.target.value})}/></label><label>Lead time (h)<input type="number" value={data.lead} onChange={e=>setData({...data,lead:+e.target.value})}/></label><label>Touch time (h)<input type="number" value={data.touch} onChange={e=>setData({...data,touch:+e.target.value})}/></label><label className="wide">Fasi principali<textarea value={data.steps} onChange={e=>setData({...data,steps:e.target.value})}/></label><label className="wide">Bottleneck / criticità<textarea value={data.pain} onChange={e=>setData({...data,pain:e.target.value})}/></label></div>}
 {msg&&<div className="msg">{msg}</div>}<button className="submit" onClick={submit}>Invia questionario</button><footer>Token: {token.slice(0,8)}… · Link personale a uso singolo</footer></section></main>
}
