import {useEffect,useState} from 'react'
import './survey-links.css'

type Item={token:string;form_code:string;recipient_name:string;recipient_email:string;active:boolean;expires_at:string;created_at:string;submitted_at:string|null}
export default function SurveyLinks(){
 const [formCode,setFormCode]=useState('F02'),[recipientName,setRecipientName]=useState(''),[recipientEmail,setRecipientEmail]=useState(''),[expiresAt,setExpiresAt]=useState(''),[items,setItems]=useState<Item[]>([]),[msg,setMsg]=useState('')
 const load=async()=>{try{const r=await fetch('/api/survey-link');const j=await r.json();if(r.ok)setItems(j.items||[]);else setMsg(j.error==='backend_not_configured'?'Backend centrale non ancora configurato su Vercel.':'Impossibile leggere i link.')}catch{setMsg('Backend non raggiungibile.')}}
 useEffect(()=>{load()},[])
 const create=async()=>{setMsg('Creazione link...');try{const r=await fetch('/api/survey-link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({formCode,recipientName,recipientEmail,expiresAt:expiresAt||null})});const j=await r.json();if(!r.ok)throw new Error(j.error||'errore');const url=`${location.origin}/survey/${formCode}/${j.token}`;await navigator.clipboard?.writeText(url);setMsg('Link creato e copiato negli appunti.');setRecipientName('');setRecipientEmail('');await load()}catch(e:any){setMsg(e.message==='backend_not_configured'?'Per attivare i link reali manca DATABASE_URL nelle Environment Variables di Vercel.':'Errore: '+e.message)}}
 const copy=(i:Item)=>navigator.clipboard?.writeText(`${location.origin}/survey/${i.form_code}/${i.token}`)
 return <main className="sl-page"><header><div><a href="/surveys">← Questionari</a><small>SURVEY DISTRIBUTION</small><h1>Link questionari</h1><p>Genera link personali monouso, controlla completamenti e scadenze senza dare accesso al gestionale.</p></div></header>
 {msg&&<div className="sl-msg">{msg}</div>}
 <section className="sl-panel"><h2>Nuovo invito</h2><div className="sl-grid"><label>Questionario<select value={formCode} onChange={e=>setFormCode(e.target.value)}><option>F01</option><option>F02</option><option>F03</option><option>F04</option></select></label><label>Destinatario<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Nome o funzione"/></label><label>Email<input value={recipientEmail} onChange={e=>setRecipientEmail(e.target.value)} placeholder="opzionale"/></label><label>Scadenza<input type="datetime-local" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/></label></div><button onClick={create}>Genera e copia link</button></section>
 <section className="sl-panel"><div className="sl-title"><h2>Registro inviti</h2><button className="secondary" onClick={load}>Aggiorna</button></div><div className="table-wrap"><table><thead><tr><th>Form</th><th>Destinatario</th><th>Creato</th><th>Scadenza</th><th>Stato</th><th></th></tr></thead><tbody>{items.length?items.map(i=><tr key={i.token}><td>{i.form_code}</td><td>{i.recipient_name||i.recipient_email||'—'}</td><td>{new Date(i.created_at).toLocaleString('it-IT')}</td><td>{i.expires_at?new Date(i.expires_at).toLocaleString('it-IT'):'—'}</td><td><b className={i.submitted_at?'done':i.active?'open':'closed'}>{i.submitted_at?'COMPLETATO':i.active?'APERTO':'CHIUSO'}</b></td><td><button className="linkbtn" onClick={()=>copy(i)}>Copia link</button></td></tr>):<tr><td colSpan={6}>Nessun invito disponibile.</td></tr>}</tbody></table></div></section>
 </main>
}
