import { useEffect, useMemo, useState } from 'react'
import './surveys.css'

type Maturity={id:string;submittedAt:string;functionName:string;respondentRole:string;scores:Record<string,number>;overall:number;notes:string}
type ProcessSurvey={id:string;submittedAt:string;name:string;functionId:string;owner:string;trigger:string;input:string;output:string;steps:string;systems:string;volume:number;lead:number;touch:number;waiting:string;rework:string;kpi:string;pain:string}
type Store={company?:any;functions?:any[];processes?:any[];tasks?:any[];opportunities?:any[];useCases?:any[];surveyLog?:any[];milestones?:any[]}

const MAT_KEY='aito-f02-maturity'
const PROC_KEY='aito-f04-process-surveys'
const STORE_KEY='aito-store'
const dimensions=[
 ['skills','Skills','Comprensione AI, verifica output, prompting e limiti'],
 ['adoption','Adoption','Frequenza e qualità dell’uso nel lavoro'],
 ['process','Process','Standardizzazione, misurabilità e ripetitività'],
 ['data','Data','Reperibilità, qualità, fonti ufficiali e permessi'],
 ['technology','Technology','Sistemi, integrazioni e strumenti disponibili'],
 ['governance','Governance','Regole, owner, KPI, rischio e ROI']
] as const
const read=<T,>(k:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'null')??fallback}catch{return fallback}}
const write=(k:string,v:any)=>localStorage.setItem(k,JSON.stringify(v))
const next=(prefix:string,n:number,w=4)=>`${prefix}-${String(n+1).padStart(w,'0')}`

export default function SurveyCenter(){
 const [tab,setTab]=useState<'control'|'f02'|'f04'>('control')
 const [maturity,setMaturity]=useState<Maturity[]>(()=>read(MAT_KEY,[]))
 const [processSurveys,setProcessSurveys]=useState<ProcessSurvey[]>(()=>read(PROC_KEY,[]))
 const [notice,setNotice]=useState('')
 const store=read<Store>(STORE_KEY,{})
 const functions=store.functions||[]
 const [f02,setF02]=useState({functionName:'',respondentRole:'',skills:3,adoption:3,process:3,data:3,technology:3,governance:3,notes:''})
 const [f04,setF04]=useState({name:'',functionId:functions[0]?.id||'',owner:'',trigger:'',input:'',output:'',steps:'',systems:'',volume:0,lead:0,touch:0,waiting:'',rework:'',kpi:'',pain:''})
 useEffect(()=>write(MAT_KEY,maturity),[maturity]); useEffect(()=>write(PROC_KEY,processSurveys),[processSurveys])
 const avg=useMemo(()=>maturity.length?Math.round(maturity.reduce((s,x)=>s+x.overall,0)/maturity.length):0,[maturity])
 const dimAvg=(k:string)=>maturity.length?Math.round(maturity.reduce((s,x)=>s+(x.scores[k]||0),0)/maturity.length*20):0
 const addLog=(form:string,summary:string)=>{const s=read<Store>(STORE_KEY,{});const log=s.surveyLog||[];write(STORE_KEY,{...s,surveyLog:[...log,{id:`SURV-${String(log.length+1).padStart(4,'0')}`,form,submittedAt:new Date().toISOString(),summary}]})}
 const submitF02=()=>{if(!f02.functionName.trim()){setNotice('Indica la funzione/area.');return};const scores:any={skills:f02.skills,adoption:f02.adoption,process:f02.process,data:f02.data,technology:f02.technology,governance:f02.governance};const weighted=(scores.skills*.15+scores.adoption*.15+scores.process*.20+scores.data*.15+scores.technology*.15+scores.governance*.20);const overall=Math.round(weighted/5*100);const rec:Maturity={id:next('MAT',maturity.length),submittedAt:new Date().toISOString(),functionName:f02.functionName,respondentRole:f02.respondentRole,scores,overall,notes:f02.notes};setMaturity(x=>[...x,rec]);addLog('F02 – AI Maturity',`${f02.functionName} · ${overall}/100`);setNotice(`Assessment registrato: ${overall}/100.`);setF02({...f02,respondentRole:'',notes:''})}
 const submitF04=()=>{if(!f04.name.trim()){setNotice('Indica il nome del processo.');return};const rec:ProcessSurvey={id:next('F04',processSurveys.length),submittedAt:new Date().toISOString(),...f04};setProcessSurveys(x=>[...x,rec]);const s=read<Store>(STORE_KEY,{});const ps=s.processes||[];const p={id:`PROC-${String(ps.length+1).padStart(4,'0')}`,name:f04.name,functionId:f04.functionId,owner:f04.owner,lead:Number(f04.lead)||0,touch:Number(f04.touch)||0,volume:Number(f04.volume)||0,pain:f04.pain||f04.rework||f04.waiting};write(STORE_KEY,{...s,processes:[...ps,p],surveyLog:[...(s.surveyLog||[]),{id:`SURV-${String((s.surveyLog||[]).length+1).padStart(4,'0')}`,form:'F04 – Process Discovery',submittedAt:new Date().toISOString(),summary:`${f04.name} · ${f04.owner||'owner da definire'}`}]});setNotice(`${p.id} creato automaticamente nel Process Inventory.`);setF04({...f04,name:'',owner:'',trigger:'',input:'',output:'',steps:'',systems:'',volume:0,lead:0,touch:0,waiting:'',rework:'',kpi:'',pain:''})}
 const exportSurveyData=()=>{const payload={format:'AI_TRANSFORMATION_SURVEY_EXPORT',version:'1.0',exported_at:new Date().toISOString(),f02_maturity:maturity,f04_process_discovery:processSurveys};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='survey-data-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 return <div className="survey-page"><header className="survey-head"><div><a href="/">← AI Transformation OS</a><small>SURVEY CONTROL CENTER</small><h1>Questionari & Assessment</h1><p>Raccogli dati strutturati, misura la maturity e alimenta automaticamente la mappa dei processi.</p></div><button onClick={exportSurveyData}>Esporta dati questionari</button></header>{notice&&<div className="survey-notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
 <nav className="survey-tabs"><button className={tab==='control'?'active':''} onClick={()=>setTab('control')}>Control Center</button><button className={tab==='f02'?'active':''} onClick={()=>setTab('f02')}>F02 · AI Maturity</button><button className={tab==='f04'?'active':''} onClick={()=>setTab('f04')}>F04 · Process Discovery</button></nav>
 {tab==='control'&&<><section className="metric-grid"><article><span>F02 completati</span><b>{maturity.length}</b></article><article><span>Maturity media</span><b>{avg}/100</b></article><article><span>F04 completati</span><b>{processSurveys.length}</b></article><article><span>Processi nel workspace</span><b>{(read<Store>(STORE_KEY,{}).processes||[]).length}</b></article></section><section className="survey-grid"><div className="panel"><h2>Maturity per dimensione</h2>{dimensions.map(([k,l])=><div className="bar-row" key={k}><span>{l}</span><i><b style={{width:`${dimAvg(k)}%`}}/></i><strong>{dimAvg(k)}</strong></div>)}</div><div className="panel"><h2>Stato raccolta</h2><p className="muted">Il Control Center sarà il punto unico per invii, completamenti e reminder. In questa release registra le compilazioni integrate; il prossimo step collega i link pubblici al database centrale.</p><div className="status-list"><div><b>F01</b><span>Organization Discovery · già integrato nel workspace</span></div><div><b>F02</b><span>{maturity.length} assessment registrati</span></div><div><b>F03</b><span>Task & Productivity · già integrato nel workspace</span></div><div><b>F04</b><span>{processSurveys.length} process discovery registrati</span></div></div></div></section><section className="panel"><h2>Ultimi assessment F02</h2><div className="survey-table"><table><thead><tr><th>ID</th><th>Funzione</th><th>Ruolo</th><th>Score</th><th>Data</th></tr></thead><tbody>{maturity.length?maturity.slice().reverse().slice(0,10).map(x=><tr key={x.id}><td>{x.id}</td><td>{x.functionName}</td><td>{x.respondentRole||'—'}</td><td><b>{x.overall}/100</b></td><td>{new Date(x.submittedAt).toLocaleString('it-IT')}</td></tr>):<tr><td colSpan={5}>Nessun F02 compilato.</td></tr>}</tbody></table></div></section></>}
 {tab==='f02'&&<section className="panel form-panel"><div className="intro"><h2>F02 – AI Maturity Assessment</h2><p>Valuta la capacità organizzativa di usare AI in modo produttivo, misurabile e governato. Scala 1 = assente/iniziale; 5 = consolidato.</p></div><div className="form-grid"><label>Funzione / area<input value={f02.functionName} onChange={e=>setF02({...f02,functionName:e.target.value})} placeholder="es. Engineering"/></label><label>Ruolo del rispondente<input value={f02.respondentRole} onChange={e=>setF02({...f02,respondentRole:e.target.value})} placeholder="es. Process Owner"/></label></div><div className="dimension-list">{dimensions.map(([k,label,help])=><div key={k}><div><b>{label}</b><small>{help}</small></div><input type="range" min="1" max="5" value={(f02 as any)[k]} onChange={e=>setF02({...f02,[k]:Number(e.target.value)})}/><strong>{(f02 as any)[k]}/5</strong></div>)}</div><label>Note / evidenze<textarea value={f02.notes} onChange={e=>setF02({...f02,notes:e.target.value})} placeholder="Esempi, strumenti usati, criticità, evidenze..."/></label><button className="primary" onClick={submitF02}>Registra F02 e calcola score</button></section>}
 {tab==='f04'&&<section className="panel form-panel"><div className="intro"><h2>F04 – Process Discovery</h2><p>Una compilazione = un processo. Il salvataggio crea automaticamente il processo nel Process Inventory principale.</p></div><div className="form-grid"><label>Nome processo<input value={f04.name} onChange={e=>setF04({...f04,name:e.target.value})}/></label><label>Funzione<select value={f04.functionId} onChange={e=>setF04({...f04,functionId:e.target.value})}>{functions.map(f=><option value={f.id} key={f.id}>{f.id} · {f.name}</option>)}</select></label><label>Process Owner<input value={f04.owner} onChange={e=>setF04({...f04,owner:e.target.value})}/></label><label>Trigger<input value={f04.trigger} onChange={e=>setF04({...f04,trigger:e.target.value})} placeholder="Evento che avvia il processo"/></label><label>Input<textarea value={f04.input} onChange={e=>setF04({...f04,input:e.target.value})}/></label><label>Output<textarea value={f04.output} onChange={e=>setF04({...f04,output:e.target.value})}/></label><label className="wide">Fasi principali<textarea value={f04.steps} onChange={e=>setF04({...f04,steps:e.target.value})} placeholder="1. ...  2. ...  3. ..."/></label><label>Sistemi / software<input value={f04.systems} onChange={e=>setF04({...f04,systems:e.target.value})}/></label><label>Volume / mese<input type="number" value={f04.volume} onChange={e=>setF04({...f04,volume:Number(e.target.value)})}/></label><label>Lead time (ore)<input type="number" value={f04.lead} onChange={e=>setF04({...f04,lead:Number(e.target.value)})}/></label><label>Touch time (ore)<input type="number" value={f04.touch} onChange={e=>setF04({...f04,touch:Number(e.target.value)})}/></label><label>Attese / approvazioni<textarea value={f04.waiting} onChange={e=>setF04({...f04,waiting:e.target.value})}/></label><label>Errori / rework<textarea value={f04.rework} onChange={e=>setF04({...f04,rework:e.target.value})}/></label><label>KPI attuali<input value={f04.kpi} onChange={e=>setF04({...f04,kpi:e.target.value})}/></label><label className="wide">Bottleneck / pain point<textarea value={f04.pain} onChange={e=>setF04({...f04,pain:e.target.value})}/></label></div><button className="primary" onClick={submitF04}>Registra F04 e crea processo</button></section>}
 </div>
}
