import {useEffect,useState} from 'react'
import './survey-inbox.css'

type Resp={id:string;form_code:string;respondent_token:string;respondent_name:string;respondent_email:string;payload:any;submitted_at:string;source:string}
const read=(k:string,f:any)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
const write=(k:string,v:any)=>localStorage.setItem(k,JSON.stringify(v))
export default function SurveyInbox(){
 const [items,setItems]=useState<Resp[]>([]),[msg,setMsg]=useState(''),[selected,setSelected]=useState<Resp|null>(null)
 const load=async()=>{setMsg('Aggiornamento...');try{const r=await fetch('/api/survey-responses');const j=await r.json();if(!r.ok)throw new Error(j.error||'errore');setItems(j.items||[]);setMsg('')}catch(e:any){setMsg(e.message==='backend_not_configured'?'Backend centrale non configurato.':'Errore: '+e.message)}}
 useEffect(()=>{load()},[])
 const isImported=(x:Resp)=>x.source==='PUBLIC_LINK_IMPORTED'
 const importOne=async(x:Resp)=>{if(isImported(x))return;setMsg('Importazione...');const s=read('aito-store',{}),p=x.payload||{};let next={...s};
  if(x.form_code==='F01'){const fs=s.functions||[];next.functions=[...fs,{id:`FUNC-${String(fs.length+1).padStart(3,'0')}`,name:p.function||p.functionName||'Funzione da definire',owner:x.respondent_name||'',people:+p.people||0,mission:p.mission||'',systems:p.systems||''}]}
  if(x.form_code==='F03'){const ts=s.tasks||[];next.tasks=[...ts,{id:`TASK-${String(ts.length+1).padStart(4,'0')}`,name:p.task||'Task da definire',processId:'',frequency:+p.frequency||0,minutes:+p.minutes||0,people:+p.participants||1,cost:+p.cost||35,repeat:+p.repeat||3,data:3,judgement:+p.judgement||3,pain:p.pain||''}]}
  if(x.form_code==='F02'){const arr=read('aito-f02-maturity',[]);const scores={skills:+p.skills||3,adoption:+p.adoption||3,process:+p.process||3,data:+p.data||3,technology:+p.technology||3,governance:+p.governance||3};const overall=Math.round((scores.skills*.15+scores.adoption*.15+scores.process*.20+scores.data*.15+scores.technology*.15+scores.governance*.20)/5*100);write('aito-f02-maturity',[...arr,{id:`MAT-${String(arr.length+1).padStart(4,'0')}`,submittedAt:x.submitted_at,functionName:p.functionName||'',respondentRole:p.role||'',scores,overall,notes:p.notes||''}])}
  if(x.form_code==='F04'){const ps=s.processes||[];next.processes=[...ps,{id:`PROC-${String(ps.length+1).padStart(4,'0')}`,name:p.processName||'Processo da definire',functionId:'',owner:p.owner||'',lead:+p.lead||0,touch:+p.touch||0,volume:+p.volume||0,pain:p.pain||p.rework||p.waiting||''}];const arr=read('aito-f04-process-surveys',[]);write('aito-f04-process-surveys',[...arr,{id:`F04-${String(arr.length+1).padStart(4,'0')}`,submittedAt:x.submitted_at,name:p.processName||'',functionId:'',owner:p.owner||'',trigger:p.trigger||'',input:p.input||'',output:p.output||'',steps:p.steps||'',systems:p.systems||'',volume:+p.volume||0,lead:+p.lead||0,touch:+p.touch||0,waiting:p.waiting||'',rework:p.rework||'',kpi:p.kpi||'',pain:p.pain||''}])}
  const log=next.surveyLog||[];next.surveyLog=[...log,{id:`SURV-${String(log.length+1).padStart(4,'0')}`,form:x.form_code+' – Public',submittedAt:x.submitted_at,summary:x.respondent_name||x.respondent_email||'Risposta pubblica'}];write('aito-store',next)
  try{const r=await fetch('/api/survey-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'errore');setItems(v=>v.map(i=>i.id===x.id?{...i,source:'PUBLIC_LINK_IMPORTED'}:i));setMsg(`${x.form_code} importato nel workspace e marcato centralmente.`)}catch(e:any){setMsg(`Dati importati localmente, ma stato centrale non aggiornato: ${e.message}`)} }
 const label=(k:string)=>({skills:'Competenze',adoption:'Adozione',process:'Processi',data:'Dati',technology:'Tecnologia',governance:'Governance',functionName:'Funzione',role:'Ruolo',task:'Task',processName:'Processo',pain:'Pain point',systems:'Sistemi',mission:'Missione'} as any)[k]||k
 return <main className="si-page"><header><a href="/surveys">← Questionari</a><small>SURVEY INBOX</small><h1>Risposte ricevute</h1><p>Rivedi le compilazioni provenienti dai link pubblici prima di inserirle nel modello aziendale.</p><button onClick={load}>Aggiorna inbox</button></header>{msg&&<div className="si-msg">{msg}</div>}<section className="si-panel"><table><thead><tr><th>Form</th><th>Rispondente</th><th>Data</th><th>Stato</th><th>Azioni</th></tr></thead><tbody>{items.length?items.map(x=><tr key={x.id}><td><b>{x.form_code}</b></td><td>{x.respondent_name||x.respondent_email||'Anonimo'}</td><td>{new Date(x.submitted_at).toLocaleString('it-IT')}</td><td>{isImported(x)?<span className="imported">IMPORTATO</span>:<span className="pending">DA RIVEDERE</span>}</td><td><button onClick={()=>setSelected(x)}>Visualizza</button> <button disabled={isImported(x)} onClick={()=>importOne(x)}>{isImported(x)?'Importato':'Importa'}</button></td></tr>):<tr><td colSpan={5}>Nessuna risposta disponibile.</td></tr>}</tbody></table></section>{selected&&<section className="si-panel"><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center'}}><div><small>{selected.form_code} · DETTAGLIO RISPOSTA</small><h2>{selected.respondent_name||selected.respondent_email||'Risposta anonima'}</h2></div><button onClick={()=>setSelected(null)}>Chiudi</button></div><p>{selected.respondent_email||''} · {new Date(selected.submitted_at).toLocaleString('it-IT')}</p><table><tbody>{Object.entries(selected.payload||{}).filter(([,v])=>v!==''&&v!==null&&v!==undefined).map(([k,v])=><tr key={k}><th>{label(k)}</th><td>{String(v)}</td></tr>)}</tbody></table></section>}</main>
}
