export const SCORING_VERSION='2.0-alpha' as const
export type Scale5=1|2|3|4|5
export type EvidenceLevel='none'|'anecdotal'|'documented'|'measured'
export type Evidence={level:EvidenceLevel;source?:string}
export type ScoreResult={score:number;confidence:number;band:string;drivers:string[];gaps:string[];scoringVersion:typeof SCORING_VERSION}
export type F01V2={schemaVersion:'F01@2.0';functionName:string;owner:string;people:number;mission:string;responsibilities:string[];outputs:string[];customers:string[];kpis:string[];performancePain?:string;dependencies:string[];incomingInputs:string[];outgoingOutputs:string[];handoffPain?:string;externalDependencies:string[];systems:string[];manualAssets:string[];criticalData:string[];knowledgeConcentration:Scale5;procedureMaturity:Scale5;topPain:string[];manualAreas:string[];expectedChanges:string[];priorities:string[];answerConfidence:Scale5}
export type F02Dimension='skills'|'adoption'|'process'|'data'|'technology'|'governance'
export type F02V2={schemaVersion:'F02@2.0';functionName?:string;role?:string;answers:Record<F02Dimension,(Scale5|null)[]>;evidence:Partial<Record<F02Dimension,Evidence>>}
export type F04V2={schemaVersion:'F04@2.0';processName:string;owner:string;purpose:string;trigger:string;output:string;customer?:string;functions:string[];annualVolume:number;people:number;touchMinutes:number;leadMinutes:number;waitMinutes:number;handoffs:number;approvals:number;systems:string[];manualTransfer:Scale5;dataReadiness:Scale5;errorProbability:number;reworkMinutes:number;impact:Scale5;keyPersonRisk:Scale5;procedureStatus:'no'|'partial'|'yes-current';ruleBased:Scale5;judgement:Scale5;inputStructure:Scale5;historicalData:Scale5;humanValidation:Scale5;integrationFeasibility:Scale5;baselineKpis:string[];targetKpis:string[];evidence:Evidence}
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));export const norm5=(n:Scale5)=>clamp((n-1)/4*100);const mean=(a:number[])=>a.length?a.reduce((s,n)=>s+n,0)/a.length:0
const evidenceValue=(x?:Evidence)=>({none:0,anecdotal:35,documented:70,measured:100}[x?.level||'none'])
export const maturityBand=(n:number)=>n<25?'INITIAL':n<45?'EMERGING':n<65?'DEFINED':n<80?'MANAGED':'OPTIMIZED'
export const confidenceBand=(n:number)=>n<40?'LOW':n<70?'MEDIUM':n<85?'GOOD':'STRONG'
export function scoreF01(x:F01V2):ScoreResult{const fields=[!!x.owner,x.people>0,!!x.mission,x.responsibilities.length>0,x.outputs.length>0,x.kpis.length>0,x.systems.length>0,x.dependencies.length>0];const weights=[20,10,10,10,10,15,10,10],base=fields.reduce((s,v,i)=>s+(v?weights[i]:0),0)+norm5(x.answerConfidence)*.05;const gaps:string[]=[];if(!x.owner)gaps.push('Owner');if(x.people<=0)gaps.push('Organico');if(!x.kpis.length)gaps.push('KPI');if(!x.outputs.length)gaps.push('Output');return{score:Math.round(clamp(base)),confidence:Math.round(norm5(x.answerConfidence)),band:base<60?'BLOCKER':base<75?'WARNING':'PASS',drivers:[`${x.systems.length} sistemi`,`${x.dependencies.length} dipendenze`,`${x.manualAreas.length} aree manuali`],gaps,scoringVersion:SCORING_VERSION}}
const dimWeights:Record<F02Dimension,number>={skills:.15,adoption:.15,process:.20,data:.20,technology:.15,governance:.15}
export function scoreF02(x:F02V2):ScoreResult&{dimensions:Record<F02Dimension,number>;criticalFloorPass:boolean}{const dims={} as Record<F02Dimension,number>,conf:number[]=[];(Object.keys(dimWeights) as F02Dimension[]).forEach(k=>{const vals=x.answers[k].filter((v):v is Scale5=>v!=null).map(norm5);dims[k]=Math.round(mean(vals));conf.push(evidenceValue(x.evidence[k]))});const score=Math.round((Object.keys(dimWeights) as F02Dimension[]).reduce((s,k)=>s+dims[k]*dimWeights[k],0)),eMean=mean(conf),documented=Object.values(x.evidence).some(e=>e?.level==='documented'||e?.level==='measured'),confidence=Math.round(documented?eMean:Math.min(60,eMean)),criticalFloorPass=dims.data>=45&&dims.governance>=45&&dims.technology>=40&&dims.skills>=40,gaps=(Object.keys(dims) as F02Dimension[]).filter(k=>dims[k]<45).map(k=>`${k} ${dims[k]}`),drivers=(Object.keys(dims) as F02Dimension[]).sort((a,b)=>dims[b]-dims[a]).slice(0,3).map(k=>`${k} ${dims[k]}`);return{score,confidence,band:maturityBand(score),dimensions:dims,criticalFloorPass,drivers,gaps,scoringVersion:SCORING_VERSION}}
export function scoreF04(x:F04V2){const efficiency=x.leadMinutes>0?clamp(x.touchMinutes/x.leadMinutes*100):0,waitingRatio=x.leadMinutes>0?clamp(x.waitMinutes/x.leadMinutes*100):0,annualWorkload=x.annualVolume*x.touchMinutes/60,annualRework=x.annualVolume*clamp(x.errorProbability,0,1)*x.reworkMinutes/60,handoff=x.handoffs===0?100:x.handoffs<=2?80:x.handoffs<=4?55:x.handoffs<=7?30:10,approval=x.approvals===0?100:x.approvals===1?80:x.approvals===2?60:x.approvals===3?40:20,procedure={no:0,partial:50,'yes-current':100}[x.procedureStatus],automation=Math.round(norm5(x.ruleBased)*.20+(100-norm5(x.judgement))*.15+norm5(x.manualTransfer)*.15+(100-efficiency)*.20+(100-handoff)*.10+(100-approval)*.10+norm5(x.dataReadiness)*.10),ai=Math.round(norm5(x.inputStructure)*.15+norm5(x.historicalData)*.15+norm5(x.dataReadiness)*.15+norm5(x.judgement)*.15+norm5(x.humanValidation)*.15+(x.baselineKpis.length?100:0)*.10+norm5(x.integrationFeasibility)*.10+(100-norm5(x.impact))*.05);return{processEfficiency:Math.round(efficiency),waitingRatio:Math.round(waitingRatio),annualWorkloadHours:Math.round(annualWorkload),annualReworkHours:Math.round(annualRework),handoffReadiness:handoff,approvalReadiness:approval,procedureReadiness:procedure,automationSuitability:clamp(automation),aiSuitability:clamp(ai),confidence:evidenceValue(x.evidence),scoringVersion:SCORING_VERSION}}
export type OpportunityEvidence={value:number;feasibility:number;riskReadiness:number;evidence:number;privacySecurityBlocker?:boolean;governanceBlocker?:boolean}
export function opportunityPriority(x:OpportunityEvidence){const score=Math.round(clamp(x.value)*.35+clamp(x.feasibility)*.30+clamp(x.riskReadiness)*.20+clamp(x.evidence)*.15);let priority=score>=75?'A':score>=60?'B':score>=45?'C':'BACKLOG';if(x.evidence<40&&priority==='A')priority='B';const pocBlocked=!!(x.privacySecurityBlocker||x.governanceBlocker);return{score,priority,pocBlocked,scoringVersion:SCORING_VERSION}}
export type ReadinessInput={data:number;securityPrivacy:number;processKpi:number;integration:number;human:number;governance:number;confidence:number;hardBlockers:string[]}
export function readinessGate(x:ReadinessInput){const score=Math.round(x.data*.20+x.securityPrivacy*.20+x.processKpi*.15+x.integration*.15+x.human*.15+x.governance*.15);const status=x.hardBlockers.length||score<60||x.confidence<40?'BLOCKER':score>=75&&x.confidence>=60?'PASS':'CONDITIONAL';return{score,status,confidence:x.confidence,hardBlockers:x.hardBlockers,scoringVersion:SCORING_VERSION}}
export const SURVEY_V2_TEST_VECTORS={f02Strong:{skills:[4,4,4,4,4],adoption:[4,4,4,4,4],process:[4,4,4,4,4],data:[4,4,4,4,4,4],technology:[4,4,4,4,4],governance:[4,4,4,4,4,4]},readinessPass:{data:80,securityPrivacy:80,processKpi:75,integration:70,human:80,governance:75,confidence:75,hardBlockers:[]},readinessBlocked:{data:90,securityPrivacy:90,processKpi:90,integration:90,human:90,governance:90,confidence:90,hardBlockers:['No accountable owner']}}
export type RegressionResult={ok:boolean;passed:number;total:number;failures:string[];scoringVersion:typeof SCORING_VERSION}
export function runSurveyV2Regression():RegressionResult{const failures:string[]=[];let passed=0;const check=(name:string,cond:boolean)=>{if(cond)passed++;else failures.push(name)};check('norm5 min',norm5(1)===0);check('norm5 mid',norm5(3)===50);check('norm5 max',norm5(5)===100);const strong:Record<F02Dimension,(Scale5|null)[]>={skills:[4,4,4,4,4],adoption:[4,4,4,4,4],process:[4,4,4,4,4],data:[4,4,4,4,4,4],technology:[4,4,4,4,4],governance:[4,4,4,4,4,4]};const f02=scoreF02({schemaVersion:'F02@2.0',answers:strong,evidence:{skills:{level:'documented'},adoption:{level:'documented'},process:{level:'documented'},data:{level:'measured'},technology:{level:'documented'},governance:{level:'documented'}}});check('F02 score 75',f02.score===75);check('F02 critical floors pass',f02.criticalFloorPass===true);check('F02 confidence >=70',f02.confidence>=70);const pass=readinessGate(SURVEY_V2_TEST_VECTORS.readinessPass);check('Readiness PASS',pass.status==='PASS');const blocked=readinessGate(SURVEY_V2_TEST_VECTORS.readinessBlocked);check('Hard blocker overrides high score',blocked.status==='BLOCKER');const lowEvidence=opportunityPriority({value:100,feasibility:100,riskReadiness:100,evidence:20});check('Low evidence prevents priority A',lowEvidence.priority!=='A');const hardRisk=opportunityPriority({value:100,feasibility:100,riskReadiness:100,evidence:100,privacySecurityBlocker:true});check('Security blocker blocks PoC',hardRisk.pocBlocked===true);const f04=scoreF04({schemaVersion:'F04@2.0',processName:'Test',owner:'Owner',purpose:'Test',trigger:'Start',output:'Output',functions:['IT'],annualVolume:1200,people:2,touchMinutes:30,leadMinutes:120,waitMinutes:60,handoffs:3,approvals:2,systems:['ERP'],manualTransfer:4,dataReadiness:4,errorProbability:.1,reworkMinutes:15,impact:2,keyPersonRisk:3,procedureStatus:'partial',ruleBased:4,judgement:2,inputStructure:4,historicalData:4,humanValidation:5,integrationFeasibility:4,baselineKpis:['lead'],targetKpis:['lead target'],evidence:{level:'measured'}});check('F04 efficiency 25',f04.processEfficiency===25);check('F04 waiting ratio 50',f04.waitingRatio===50);check('F04 workload 600h',f04.annualWorkloadHours===600);const total=13;return{ok:failures.length===0&&passed===total,passed,total,failures,scoringVersion:SCORING_VERSION}}
