import {useEffect,useMemo,useState} from 'react'
import './v1-readiness.css'
const read=(k:string,f:any)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},norm=(s:any)=>String(s||'').trim().toLowerCase()
type Status='OK'|'WARNING'|'BLOCKER'
type Check={name:string;status:Status;detail:string;action:string;href:string}
type Invite={form_code:string;function_name?:string;recipient_email?:string;recipient_role?:string;submitted_at?:string|null}
export default function V1Readiness(){
 const [api,setApi]=useState<Record<string,boolean|null>>({journey:null,surveys:null,responses:null,workspace:null}),[auth,setAuth]=useState<{configured:boolean;authenticated:boolean}|null>(null),[invites,setInvites]=useState<Invite[]>([]),[stamp,setStamp]=useState('');
 const data=read('aito-store',{});
 const run=async()=>{setApi({journey:null,surveys:null,responses:null,workspace:null});setAuth(null);const out:any={};try{const r=await fetch('/api/auth-status'),j=await r.json();setAuth({configured:!!j.configured,authenticated:!!j.authenticated})}catch{setAuth({configured:false,authenticated:false})}try{const r=await fetch('/api/survey-link'),j=await r.json();out.surveys=r.ok;if(r.ok)setInvites(j.items||[])}catch{out.surveys=false}for(const [k,u] of [['journey','/api/journey-state'],['responses','/api/survey-responses'],['workspace','/api/workspace-state']] as const){try{const r=await fetch(u);out[k]=r.ok}catch{out[k]=false}}setApi(out);setStamp(new Date().toLocaleString('it-IT'))};
 useEffect(()=>{run()},[]);
 const x=useMemo(()=>{
  const funcs=(data.functions||[]).filter((f:any)=>f.name&&(+f.people||0)>0),draft=(data.functions||[]).filter((f:any)=>(+f.people||0)<=0),ins=data.employeeInsights||[],opps=data.opportunities||[],useCases=data.useCases||[];
  const missingOwners=funcs.filter((f:any)=>!String(f.owner||'').trim()),f03=invites.filter(i=>i.form_code==='F03');
  const outside=f03.filter(i=>i.function_name&&!funcs.some((f:any)=>norm(f.name)===norm(i.function_name)));
  const dup=new Map<string,number>();f03.forEach(i=>{const k=[norm(i.recipient_email),norm(i.function_name),norm(i.recipient_role)].join('|');if(k.replaceAll('|',''))dup.set(k,(dup.get(k)||0)+1)});const duplicates=[...dup.values()].filter(n=>n>1).length;
  const bcReady=useCases.some((u:any)=>u.kpi&&(+u.baseline||0)>0&&(+u.setup||0)+(+u.opex||0)>0&&(+u.benefit||0)>0);
  const benefitsReady=useCases.some((u:any)=>u.measure&&((+u.measure.afterTime||0)>0||(+u.measure.afterQuality||0)>0||(+u.measure.afterThroughput||0)>0));
  const checks:Check[]=[
   {name:'Build e frontend',status:'OK',detail:'Applicazione caricata dal bundle production.',action:'Nessuna azione richiesta.',href:'/?tab=dashboard'},
   {name:'Protezione accesso manager',status:auth===null?'WARNING':auth.configured?'OK':'BLOCKER',detail:auth?.configured?'Accesso manager protetto da sessione server-side.':'AITO_MANAGER_PASSWORD non è configurata: le API manageriali restano in modalità compatibilità.',action:auth?.configured?'Nessuna azione richiesta.':'Configura AITO_MANAGER_PASSWORD nelle Environment Variables del progetto Vercel e ridistribuisci.',href:'/?tab=data'},
   {name:'Workspace centrale',status:api.workspace===null?'WARNING':api.workspace?'OK':'BLOCKER',detail:api.workspace?'API workspace centrale raggiungibile.':'Il salvataggio/caricamento centrale non è raggiungibile.',action:'Verifica Central Workspace e riprova il test.',href:'/?tab=data'},
   {name:'Journey cloud API',status:api.journey===null?'WARNING':api.journey?'OK':'BLOCKER',detail:api.journey?'Storico Journey/Neon raggiungibile.':'Lo storico del Percorso Guidato non è raggiungibile.',action:'Apri il Journey e verifica la sincronizzazione cloud.',href:'/journey'},
   {name:'Survey registry API',status:api.surveys===null?'WARNING':api.surveys?'OK':'BLOCKER',detail:api.surveys?`Registro inviti centrale raggiungibile · ${f03.length} F03.`:'Il registro inviti F03 non è raggiungibile.',action:'Apri Campaign Manager e verifica il registro inviti.',href:'/survey-campaign'},
   {name:'Survey responses API',status:api.responses===null?'WARNING':api.responses?'OK':'BLOCKER',detail:api.responses?'Inbox risposte centrale raggiungibile.':'L’API delle risposte non è raggiungibile.',action:'Apri Survey Inbox e verifica il caricamento.',href:'/survey-inbox'},
   {name:'Baseline organizzativa',status:!funcs.length?'BLOCKER':missingOwners.length?'BLOCKER':'OK',detail:!funcs.length?'Nessuna funzione attiva con organico > 0.':missingOwners.length?`Owner mancanti: ${missingOwners.map((f:any)=>f.name).join(', ')}.`:`${funcs.length} funzioni attive · ${funcs.reduce((s:number,f:any)=>s+(+f.people||0),0)} persone.`,action:!funcs.length?'Definisci almeno una funzione con organico reale.':missingOwners.length?'Assegna gli owner mancanti alle funzioni attive.':'Baseline pronta.',href:'/?tab=functions'},
   {name:'Funzioni fuori baseline',status:draft.length?'WARNING':'OK',detail:draft.length?`${draft.length} funzioni con organico 0 restano fuori dalla discovery.`:'Nessuna funzione bozza fuori baseline.',action:draft.length?'Conferma se devono restare fuori perimetro oppure assegna un organico.':'Nessuna azione richiesta.',href:'/?tab=functions'},
   {name:'Coerenza inviti F03',status:outside.length?'BLOCKER':duplicates?'WARNING':'OK',detail:outside.length?`${outside.length} inviti del registro centrale sono associati a funzioni non attive nella baseline.`:duplicates?`${duplicates} possibili gruppi di inviti duplicati nel registro centrale.`:'Registro centrale coerente con la baseline e senza duplicazioni evidenti.',action:outside.length?'Correggi funzione degli invitati o aggiorna il Company Model.':duplicates?'Verifica e rimuovi eventuali inviti F03 duplicati.':'Nessuna azione richiesta.',href:'/survey-campaign'},
   {name:'Work Discovery',status:ins.length>=5?'OK':'WARNING',detail:`${ins.length} interviste F03 importate.`,action:ins.length>=5?'Verifica Coverage e Confidence.':'Completa/importa almeno 5 interviste per il collaudo operativo.',href:'/survey-coverage'},
   {name:'Opportunity Analysis',status:opps.length?'OK':'WARNING',detail:`${opps.length} opportunità nel modello.`,action:opps.length?'Verifica ranking e priorità.':'Genera almeno una opportunità dalle evidenze.',href:'/opportunity-engine'},
   {name:'Business Case',status:bcReady?'OK':'WARNING',detail:bcReady?'Almeno un use case contiene baseline, costi e benefici.':'Nessun business case completo rilevato.',action:bcReady?'Verifica ROI/payback.':'Completa almeno un business case con KPI, baseline, costi e benefici.',href:'/business-case'},
   {name:'Benefits evidence',status:benefitsReady?'OK':'WARNING',detail:benefitsReady?'È presente almeno una misura AFTER.':'Nessuna misura AFTER registrata; è normale prima dei PoC.',action:benefitsReady?'Verifica confronto BEFORE/AFTER.':'Dopo il PoC registra le misure reali.',href:'/benefits'}
  ];
  const blockers=checks.filter(c=>c.status==='BLOCKER'),warnings=checks.filter(c=>c.status==='WARNING'),ok=checks.filter(c=>c.status==='OK'),score=Math.round((ok.length+warnings.length*.5)/checks.length*100),release=blockers.length?'NON PRONTA':warnings.length?'PRONTA CON WARNING':'PRONTA',next=blockers[0]||warnings[0];
  return{checks,blockers,warnings,ok,score,release,next};
 },[api,auth,data,invites]);
 return <main className="v1"><header><div><a href="/journey">← Percorso guidato</a><small>RELEASE CONTROL · SELF TEST</small><h1>V1 Readiness</h1><p>Collaudo tecnico e operativo con indicazione esplicita di cosa correggere e dove intervenire.</p></div><button onClick={run}>Riesegui test</button></header>
 <section className="v1-hero"><div><small>STATO RELEASE</small><h2>{x.release}</h2><p>{x.blockers.length?`${x.blockers.length} BLOCKER · ${x.warnings.length} WARNING`:`0 BLOCKER · ${x.warnings.length} WARNING`}</p></div><div><b>{x.score}%</b><span>readiness osservata</span></div><div><b>{x.ok.length}/{x.checks.length}</b><span>controlli OK</span></div></section>
 {x.next&&<section className="v1-panel" style={{border:'2px solid #172033'}}><small>PROSSIMA CORREZIONE</small><h2>{x.next.name}</h2><p><b>{x.next.status}</b> · {x.next.action}</p><a href={x.next.href}>Risolvi ora →</a></section>}
 <section className="v1-panel"><h2>Controlli e azioni</h2>{x.checks.map(c=><article key={c.name}><strong className={c.status==='BLOCKER'?'FAIL':c.status==='WARNING'?'WARN':'OK'}>{c.status}</strong><div><b>{c.name}</b><p>{c.detail}</p><small><b>Azione:</b> {c.action}</small></div><a href={c.href}>{c.status==='OK'?'Apri':'Risolvi'} →</a></article>)}</section>
 <section className="v1-grid"><div className="v1-panel"><h2>Criterio V1.0</h2><p><b>PRONTA</b>: nessun blocker o warning. <b>PRONTA CON WARNING</b>: nessun blocker ma restano verifiche non bloccanti. <b>NON PRONTA</b>: almeno un blocker tecnico, di sicurezza o di coerenza dati.</p></div><div className="v1-panel"><h2>Uso consigliato</h2><p>Risolvi prima i BLOCKER nell’ordine proposto, quindi i WARNING. Riesegui il self-test dopo ogni correzione importante.</p><a href="/journey">Torna al Percorso Guidato →</a></div></section>
 <footer>Ultimo self-test: {stamp||'in corso'} · Il readiness check verifica disponibilità tecnica e coerenza minima; il collaudo finale richiede dati reali.</footer></main>}
